// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingfs/llm-tracelab/ent/dao/apitoken"
	"github.com/kingfs/llm-tracelab/ent/dao/user"
)

// APITokenCreate is the builder for creating a APIToken entity.
type APITokenCreate struct {
	config
	mutation *APITokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *APITokenCreate) SetName(v string) *APITokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *APITokenCreate) SetTokenHash(v string) *APITokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetPrefix sets the "prefix" field.
func (_c *APITokenCreate) SetPrefix(v string) *APITokenCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *APITokenCreate) SetScope(v string) *APITokenCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableScope(v *string) *APITokenCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *APITokenCreate) SetEnabled(v bool) *APITokenCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableEnabled(v *bool) *APITokenCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APITokenCreate) SetCreatedAt(v time.Time) *APITokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableCreatedAt(v *time.Time) *APITokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *APITokenCreate) SetExpiresAt(v time.Time) *APITokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableExpiresAt(v *time.Time) *APITokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *APITokenCreate) SetLastUsedAt(v time.Time) *APITokenCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableLastUsedAt(v *time.Time) *APITokenCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *APITokenCreate) SetUserID(id int) *APITokenCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *APITokenCreate) SetUser(v *User) *APITokenCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the APITokenMutation object of the builder.
func (_c *APITokenCreate) Mutation() *APITokenMutation {
	return _c.mutation
}

// Save creates the APIToken in the database.
func (_c *APITokenCreate) Save(ctx context.Context) (*APIToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APITokenCreate) SaveX(ctx context.Context) *APIToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APITokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APITokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APITokenCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := apitoken.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := apitoken.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apitoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APITokenCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`dao: missing required field "APIToken.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := apitoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`dao: validator failed for field "APIToken.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`dao: missing required field "APIToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := apitoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`dao: validator failed for field "APIToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		return &ValidationError{Name: "prefix", err: errors.New(`dao: missing required field "APIToken.prefix"`)}
	}
	if v, ok := _c.mutation.Prefix(); ok {
		if err := apitoken.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`dao: validator failed for field "APIToken.prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`dao: missing required field "APIToken.scope"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`dao: missing required field "APIToken.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`dao: missing required field "APIToken.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`dao: missing required edge "APIToken.user"`)}
	}
	return nil
}

func (_c *APITokenCreate) sqlSave(ctx context.Context) (*APIToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APITokenCreate) createSpec() (*APIToken, *sqlgraph.CreateSpec) {
	var (
		_node = &APIToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apitoken.Table, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.APIToken
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(apitoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(apitoken.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(apitoken.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(apitoken.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apitoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(apitoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.UserTable,
			Columns: []string{apitoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.APIToken
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIToken.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APITokenUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *APITokenCreate) OnConflict(opts ...sql.ConflictOption) *APITokenUpsertOne {
	_c.conflict = opts
	return &APITokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APITokenCreate) OnConflictColumns(columns ...string) *APITokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APITokenUpsertOne{
		create: _c,
	}
}

type (
	// APITokenUpsertOne is the builder for "upsert"-ing
	//  one APIToken node.
	APITokenUpsertOne struct {
		create *APITokenCreate
	}

	// APITokenUpsert is the "OnConflict" setter.
	APITokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *APITokenUpsert) SetName(v string) *APITokenUpsert {
	u.Set(apitoken.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *APITokenUpsert) UpdateName() *APITokenUpsert {
	u.SetExcluded(apitoken.FieldName)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *APITokenUpsert) SetTokenHash(v string) *APITokenUpsert {
	u.Set(apitoken.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *APITokenUpsert) UpdateTokenHash() *APITokenUpsert {
	u.SetExcluded(apitoken.FieldTokenHash)
	return u
}

// SetPrefix sets the "prefix" field.
func (u *APITokenUpsert) SetPrefix(v string) *APITokenUpsert {
	u.Set(apitoken.FieldPrefix, v)
	return u
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *APITokenUpsert) UpdatePrefix() *APITokenUpsert {
	u.SetExcluded(apitoken.FieldPrefix)
	return u
}

// SetScope sets the "scope" field.
func (u *APITokenUpsert) SetScope(v string) *APITokenUpsert {
	u.Set(apitoken.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *APITokenUpsert) UpdateScope() *APITokenUpsert {
	u.SetExcluded(apitoken.FieldScope)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *APITokenUpsert) SetEnabled(v bool) *APITokenUpsert {
	u.Set(apitoken.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APITokenUpsert) UpdateEnabled() *APITokenUpsert {
	u.SetExcluded(apitoken.FieldEnabled)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *APITokenUpsert) SetExpiresAt(v time.Time) *APITokenUpsert {
	u.Set(apitoken.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *APITokenUpsert) UpdateExpiresAt() *APITokenUpsert {
	u.SetExcluded(apitoken.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *APITokenUpsert) ClearExpiresAt() *APITokenUpsert {
	u.SetNull(apitoken.FieldExpiresAt)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *APITokenUpsert) SetLastUsedAt(v time.Time) *APITokenUpsert {
	u.Set(apitoken.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *APITokenUpsert) UpdateLastUsedAt() *APITokenUpsert {
	u.SetExcluded(apitoken.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *APITokenUpsert) ClearLastUsedAt() *APITokenUpsert {
	u.SetNull(apitoken.FieldLastUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APITokenUpsertOne) UpdateNewValues() *APITokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apitoken.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APITokenUpsertOne) Ignore() *APITokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APITokenUpsertOne) DoNothing() *APITokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APITokenCreate.OnConflict
// documentation for more info.
func (u *APITokenUpsertOne) Update(set func(*APITokenUpsert)) *APITokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APITokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *APITokenUpsertOne) SetName(v string) *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *APITokenUpsertOne) UpdateName() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateName()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *APITokenUpsertOne) SetTokenHash(v string) *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *APITokenUpsertOne) UpdateTokenHash() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateTokenHash()
	})
}

// SetPrefix sets the "prefix" field.
func (u *APITokenUpsertOne) SetPrefix(v string) *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.SetPrefix(v)
	})
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *APITokenUpsertOne) UpdatePrefix() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdatePrefix()
	})
}

// SetScope sets the "scope" field.
func (u *APITokenUpsertOne) SetScope(v string) *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *APITokenUpsertOne) UpdateScope() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateScope()
	})
}

// SetEnabled sets the "enabled" field.
func (u *APITokenUpsertOne) SetEnabled(v bool) *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APITokenUpsertOne) UpdateEnabled() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateEnabled()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *APITokenUpsertOne) SetExpiresAt(v time.Time) *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *APITokenUpsertOne) UpdateExpiresAt() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *APITokenUpsertOne) ClearExpiresAt() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *APITokenUpsertOne) SetLastUsedAt(v time.Time) *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *APITokenUpsertOne) UpdateLastUsedAt() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *APITokenUpsertOne) ClearLastUsedAt() *APITokenUpsertOne {
	return u.Update(func(s *APITokenUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *APITokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for APITokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APITokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APITokenUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APITokenUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APITokenCreateBulk is the builder for creating many APIToken entities in bulk.
type APITokenCreateBulk struct {
	config
	err      error
	builders []*APITokenCreate
	conflict []sql.ConflictOption
}

// Save creates the APIToken entities in the database.
func (_c *APITokenCreateBulk) Save(ctx context.Context) ([]*APIToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APITokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APITokenCreateBulk) SaveX(ctx context.Context) []*APIToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APITokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APITokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APITokenUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *APITokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *APITokenUpsertBulk {
	_c.conflict = opts
	return &APITokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APITokenCreateBulk) OnConflictColumns(columns ...string) *APITokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APITokenUpsertBulk{
		create: _c,
	}
}

// APITokenUpsertBulk is the builder for "upsert"-ing
// a bulk of APIToken nodes.
type APITokenUpsertBulk struct {
	create *APITokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APITokenUpsertBulk) UpdateNewValues() *APITokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apitoken.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APITokenUpsertBulk) Ignore() *APITokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APITokenUpsertBulk) DoNothing() *APITokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APITokenCreateBulk.OnConflict
// documentation for more info.
func (u *APITokenUpsertBulk) Update(set func(*APITokenUpsert)) *APITokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APITokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *APITokenUpsertBulk) SetName(v string) *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *APITokenUpsertBulk) UpdateName() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateName()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *APITokenUpsertBulk) SetTokenHash(v string) *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *APITokenUpsertBulk) UpdateTokenHash() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateTokenHash()
	})
}

// SetPrefix sets the "prefix" field.
func (u *APITokenUpsertBulk) SetPrefix(v string) *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.SetPrefix(v)
	})
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *APITokenUpsertBulk) UpdatePrefix() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdatePrefix()
	})
}

// SetScope sets the "scope" field.
func (u *APITokenUpsertBulk) SetScope(v string) *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *APITokenUpsertBulk) UpdateScope() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateScope()
	})
}

// SetEnabled sets the "enabled" field.
func (u *APITokenUpsertBulk) SetEnabled(v bool) *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APITokenUpsertBulk) UpdateEnabled() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateEnabled()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *APITokenUpsertBulk) SetExpiresAt(v time.Time) *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *APITokenUpsertBulk) UpdateExpiresAt() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *APITokenUpsertBulk) ClearExpiresAt() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *APITokenUpsertBulk) SetLastUsedAt(v time.Time) *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *APITokenUpsertBulk) UpdateLastUsedAt() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *APITokenUpsertBulk) ClearLastUsedAt() *APITokenUpsertBulk {
	return u.Update(func(s *APITokenUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *APITokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("dao: OnConflict was set for builder %d. Set it on the APITokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for APITokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APITokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
