// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingfs/llm-tracelab/ent/dao/executionevent"
)

// ExecutionEventCreate is the builder for creating a ExecutionEvent entity.
type ExecutionEventCreate struct {
	config
	mutation *ExecutionEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResponseID sets the "response_id" field.
func (_c *ExecutionEventCreate) SetResponseID(v string) *ExecutionEventCreate {
	_c.mutation.SetResponseID(v)
	return _c
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (_c *ExecutionEventCreate) SetNillableResponseID(v *string) *ExecutionEventCreate {
	if v != nil {
		_c.SetResponseID(*v)
	}
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *ExecutionEventCreate) SetConversationID(v string) *ExecutionEventCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_c *ExecutionEventCreate) SetNillableConversationID(v *string) *ExecutionEventCreate {
	if v != nil {
		_c.SetConversationID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *ExecutionEventCreate) SetEventType(v string) *ExecutionEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetPhase sets the "phase" field.
func (_c *ExecutionEventCreate) SetPhase(v string) *ExecutionEventCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *ExecutionEventCreate) SetNillablePhase(v *string) *ExecutionEventCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExecutionEventCreate) SetStatus(v string) *ExecutionEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExecutionEventCreate) SetNillableStatus(v *string) *ExecutionEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *ExecutionEventCreate) SetMessage(v string) *ExecutionEventCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *ExecutionEventCreate) SetNillableMessage(v *string) *ExecutionEventCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetDetailsJSON sets the "details_json" field.
func (_c *ExecutionEventCreate) SetDetailsJSON(v map[string]interface{}) *ExecutionEventCreate {
	_c.mutation.SetDetailsJSON(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *ExecutionEventCreate) SetOccurredAt(v time.Time) *ExecutionEventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_c *ExecutionEventCreate) SetNillableOccurredAt(v *time.Time) *ExecutionEventCreate {
	if v != nil {
		_c.SetOccurredAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExecutionEventCreate) SetID(v string) *ExecutionEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ExecutionEventMutation object of the builder.
func (_c *ExecutionEventCreate) Mutation() *ExecutionEventMutation {
	return _c.mutation
}

// Save creates the ExecutionEvent in the database.
func (_c *ExecutionEventCreate) Save(ctx context.Context) (*ExecutionEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExecutionEventCreate) SaveX(ctx context.Context) *ExecutionEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExecutionEventCreate) defaults() {
	if _, ok := _c.mutation.Phase(); !ok {
		v := executionevent.DefaultPhase
		_c.mutation.SetPhase(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := executionevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		v := executionevent.DefaultOccurredAt()
		_c.mutation.SetOccurredAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExecutionEventCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`dao: missing required field "ExecutionEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := executionevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`dao: validator failed for field "ExecutionEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`dao: missing required field "ExecutionEvent.phase"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`dao: missing required field "ExecutionEvent.status"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`dao: missing required field "ExecutionEvent.occurred_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := executionevent.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`dao: validator failed for field "ExecutionEvent.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ExecutionEventCreate) sqlSave(ctx context.Context) (*ExecutionEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ExecutionEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExecutionEventCreate) createSpec() (*ExecutionEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ExecutionEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(executionevent.Table, sqlgraph.NewFieldSpec(executionevent.FieldID, field.TypeString))
	)
	_spec.Schema = _c.schemaConfig.ExecutionEvent
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ResponseID(); ok {
		_spec.SetField(executionevent.FieldResponseID, field.TypeString, value)
		_node.ResponseID = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(executionevent.FieldConversationID, field.TypeString, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(executionevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(executionevent.FieldPhase, field.TypeString, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(executionevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(executionevent.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.DetailsJSON(); ok {
		_spec.SetField(executionevent.FieldDetailsJSON, field.TypeJSON, value)
		_node.DetailsJSON = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(executionevent.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExecutionEvent.Create().
//		SetResponseID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExecutionEventUpsert) {
//			SetResponseID(v+v).
//		}).
//		Exec(ctx)
func (_c *ExecutionEventCreate) OnConflict(opts ...sql.ConflictOption) *ExecutionEventUpsertOne {
	_c.conflict = opts
	return &ExecutionEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExecutionEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExecutionEventCreate) OnConflictColumns(columns ...string) *ExecutionEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExecutionEventUpsertOne{
		create: _c,
	}
}

type (
	// ExecutionEventUpsertOne is the builder for "upsert"-ing
	//  one ExecutionEvent node.
	ExecutionEventUpsertOne struct {
		create *ExecutionEventCreate
	}

	// ExecutionEventUpsert is the "OnConflict" setter.
	ExecutionEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetResponseID sets the "response_id" field.
func (u *ExecutionEventUpsert) SetResponseID(v string) *ExecutionEventUpsert {
	u.Set(executionevent.FieldResponseID, v)
	return u
}

// UpdateResponseID sets the "response_id" field to the value that was provided on create.
func (u *ExecutionEventUpsert) UpdateResponseID() *ExecutionEventUpsert {
	u.SetExcluded(executionevent.FieldResponseID)
	return u
}

// ClearResponseID clears the value of the "response_id" field.
func (u *ExecutionEventUpsert) ClearResponseID() *ExecutionEventUpsert {
	u.SetNull(executionevent.FieldResponseID)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ExecutionEventUpsert) SetConversationID(v string) *ExecutionEventUpsert {
	u.Set(executionevent.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ExecutionEventUpsert) UpdateConversationID() *ExecutionEventUpsert {
	u.SetExcluded(executionevent.FieldConversationID)
	return u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ExecutionEventUpsert) ClearConversationID() *ExecutionEventUpsert {
	u.SetNull(executionevent.FieldConversationID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *ExecutionEventUpsert) SetEventType(v string) *ExecutionEventUpsert {
	u.Set(executionevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *ExecutionEventUpsert) UpdateEventType() *ExecutionEventUpsert {
	u.SetExcluded(executionevent.FieldEventType)
	return u
}

// SetPhase sets the "phase" field.
func (u *ExecutionEventUpsert) SetPhase(v string) *ExecutionEventUpsert {
	u.Set(executionevent.FieldPhase, v)
	return u
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *ExecutionEventUpsert) UpdatePhase() *ExecutionEventUpsert {
	u.SetExcluded(executionevent.FieldPhase)
	return u
}

// SetStatus sets the "status" field.
func (u *ExecutionEventUpsert) SetStatus(v string) *ExecutionEventUpsert {
	u.Set(executionevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExecutionEventUpsert) UpdateStatus() *ExecutionEventUpsert {
	u.SetExcluded(executionevent.FieldStatus)
	return u
}

// SetMessage sets the "message" field.
func (u *ExecutionEventUpsert) SetMessage(v string) *ExecutionEventUpsert {
	u.Set(executionevent.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ExecutionEventUpsert) UpdateMessage() *ExecutionEventUpsert {
	u.SetExcluded(executionevent.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *ExecutionEventUpsert) ClearMessage() *ExecutionEventUpsert {
	u.SetNull(executionevent.FieldMessage)
	return u
}

// SetDetailsJSON sets the "details_json" field.
func (u *ExecutionEventUpsert) SetDetailsJSON(v map[string]interface{}) *ExecutionEventUpsert {
	u.Set(executionevent.FieldDetailsJSON, v)
	return u
}

// UpdateDetailsJSON sets the "details_json" field to the value that was provided on create.
func (u *ExecutionEventUpsert) UpdateDetailsJSON() *ExecutionEventUpsert {
	u.SetExcluded(executionevent.FieldDetailsJSON)
	return u
}

// ClearDetailsJSON clears the value of the "details_json" field.
func (u *ExecutionEventUpsert) ClearDetailsJSON() *ExecutionEventUpsert {
	u.SetNull(executionevent.FieldDetailsJSON)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExecutionEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(executionevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExecutionEventUpsertOne) UpdateNewValues() *ExecutionEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(executionevent.FieldID)
		}
		if _, exists := u.create.mutation.OccurredAt(); exists {
			s.SetIgnore(executionevent.FieldOccurredAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExecutionEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExecutionEventUpsertOne) Ignore() *ExecutionEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExecutionEventUpsertOne) DoNothing() *ExecutionEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExecutionEventCreate.OnConflict
// documentation for more info.
func (u *ExecutionEventUpsertOne) Update(set func(*ExecutionEventUpsert)) *ExecutionEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExecutionEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetResponseID sets the "response_id" field.
func (u *ExecutionEventUpsertOne) SetResponseID(v string) *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetResponseID(v)
	})
}

// UpdateResponseID sets the "response_id" field to the value that was provided on create.
func (u *ExecutionEventUpsertOne) UpdateResponseID() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateResponseID()
	})
}

// ClearResponseID clears the value of the "response_id" field.
func (u *ExecutionEventUpsertOne) ClearResponseID() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearResponseID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ExecutionEventUpsertOne) SetConversationID(v string) *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ExecutionEventUpsertOne) UpdateConversationID() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ExecutionEventUpsertOne) ClearConversationID() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearConversationID()
	})
}

// SetEventType sets the "event_type" field.
func (u *ExecutionEventUpsertOne) SetEventType(v string) *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *ExecutionEventUpsertOne) UpdateEventType() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateEventType()
	})
}

// SetPhase sets the "phase" field.
func (u *ExecutionEventUpsertOne) SetPhase(v string) *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *ExecutionEventUpsertOne) UpdatePhase() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdatePhase()
	})
}

// SetStatus sets the "status" field.
func (u *ExecutionEventUpsertOne) SetStatus(v string) *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExecutionEventUpsertOne) UpdateStatus() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *ExecutionEventUpsertOne) SetMessage(v string) *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ExecutionEventUpsertOne) UpdateMessage() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *ExecutionEventUpsertOne) ClearMessage() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearMessage()
	})
}

// SetDetailsJSON sets the "details_json" field.
func (u *ExecutionEventUpsertOne) SetDetailsJSON(v map[string]interface{}) *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetDetailsJSON(v)
	})
}

// UpdateDetailsJSON sets the "details_json" field to the value that was provided on create.
func (u *ExecutionEventUpsertOne) UpdateDetailsJSON() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateDetailsJSON()
	})
}

// ClearDetailsJSON clears the value of the "details_json" field.
func (u *ExecutionEventUpsertOne) ClearDetailsJSON() *ExecutionEventUpsertOne {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearDetailsJSON()
	})
}

// Exec executes the query.
func (u *ExecutionEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for ExecutionEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExecutionEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExecutionEventUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("dao: ExecutionEventUpsertOne.ID is not supported by MySQL driver. Use ExecutionEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExecutionEventUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExecutionEventCreateBulk is the builder for creating many ExecutionEvent entities in bulk.
type ExecutionEventCreateBulk struct {
	config
	err      error
	builders []*ExecutionEventCreate
	conflict []sql.ConflictOption
}

// Save creates the ExecutionEvent entities in the database.
func (_c *ExecutionEventCreateBulk) Save(ctx context.Context) ([]*ExecutionEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExecutionEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExecutionEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExecutionEventCreateBulk) SaveX(ctx context.Context) []*ExecutionEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExecutionEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExecutionEventUpsert) {
//			SetResponseID(v+v).
//		}).
//		Exec(ctx)
func (_c *ExecutionEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExecutionEventUpsertBulk {
	_c.conflict = opts
	return &ExecutionEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExecutionEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExecutionEventCreateBulk) OnConflictColumns(columns ...string) *ExecutionEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExecutionEventUpsertBulk{
		create: _c,
	}
}

// ExecutionEventUpsertBulk is the builder for "upsert"-ing
// a bulk of ExecutionEvent nodes.
type ExecutionEventUpsertBulk struct {
	create *ExecutionEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExecutionEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(executionevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExecutionEventUpsertBulk) UpdateNewValues() *ExecutionEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(executionevent.FieldID)
			}
			if _, exists := b.mutation.OccurredAt(); exists {
				s.SetIgnore(executionevent.FieldOccurredAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExecutionEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExecutionEventUpsertBulk) Ignore() *ExecutionEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExecutionEventUpsertBulk) DoNothing() *ExecutionEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExecutionEventCreateBulk.OnConflict
// documentation for more info.
func (u *ExecutionEventUpsertBulk) Update(set func(*ExecutionEventUpsert)) *ExecutionEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExecutionEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetResponseID sets the "response_id" field.
func (u *ExecutionEventUpsertBulk) SetResponseID(v string) *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetResponseID(v)
	})
}

// UpdateResponseID sets the "response_id" field to the value that was provided on create.
func (u *ExecutionEventUpsertBulk) UpdateResponseID() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateResponseID()
	})
}

// ClearResponseID clears the value of the "response_id" field.
func (u *ExecutionEventUpsertBulk) ClearResponseID() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearResponseID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ExecutionEventUpsertBulk) SetConversationID(v string) *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ExecutionEventUpsertBulk) UpdateConversationID() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ExecutionEventUpsertBulk) ClearConversationID() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearConversationID()
	})
}

// SetEventType sets the "event_type" field.
func (u *ExecutionEventUpsertBulk) SetEventType(v string) *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *ExecutionEventUpsertBulk) UpdateEventType() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateEventType()
	})
}

// SetPhase sets the "phase" field.
func (u *ExecutionEventUpsertBulk) SetPhase(v string) *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *ExecutionEventUpsertBulk) UpdatePhase() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdatePhase()
	})
}

// SetStatus sets the "status" field.
func (u *ExecutionEventUpsertBulk) SetStatus(v string) *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExecutionEventUpsertBulk) UpdateStatus() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *ExecutionEventUpsertBulk) SetMessage(v string) *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ExecutionEventUpsertBulk) UpdateMessage() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *ExecutionEventUpsertBulk) ClearMessage() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearMessage()
	})
}

// SetDetailsJSON sets the "details_json" field.
func (u *ExecutionEventUpsertBulk) SetDetailsJSON(v map[string]interface{}) *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.SetDetailsJSON(v)
	})
}

// UpdateDetailsJSON sets the "details_json" field to the value that was provided on create.
func (u *ExecutionEventUpsertBulk) UpdateDetailsJSON() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.UpdateDetailsJSON()
	})
}

// ClearDetailsJSON clears the value of the "details_json" field.
func (u *ExecutionEventUpsertBulk) ClearDetailsJSON() *ExecutionEventUpsertBulk {
	return u.Update(func(s *ExecutionEventUpsert) {
		s.ClearDetailsJSON()
	})
}

// Exec executes the query.
func (u *ExecutionEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("dao: OnConflict was set for builder %d. Set it on the ExecutionEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for ExecutionEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExecutionEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
