// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingfs/llm-tracelab/ent/dao/internal"
	"github.com/kingfs/llm-tracelab/ent/dao/parsejob"
	"github.com/kingfs/llm-tracelab/ent/dao/predicate"
)

// ParseJobUpdate is the builder for updating ParseJob entities.
type ParseJobUpdate struct {
	config
	hooks     []Hook
	mutation  *ParseJobMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ParseJobUpdate builder.
func (_u *ParseJobUpdate) Where(ps ...predicate.ParseJob) *ParseJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTraceID sets the "trace_id" field.
func (_u *ParseJobUpdate) SetTraceID(v string) *ParseJobUpdate {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *ParseJobUpdate) SetNillableTraceID(v *string) *ParseJobUpdate {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ParseJobUpdate) SetStatus(v string) *ParseJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ParseJobUpdate) SetNillableStatus(v *string) *ParseJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *ParseJobUpdate) SetAttempts(v int) *ParseJobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *ParseJobUpdate) SetNillableAttempts(v *int) *ParseJobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *ParseJobUpdate) AddAttempts(v int) *ParseJobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ParseJobUpdate) SetLastError(v string) *ParseJobUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ParseJobUpdate) SetNillableLastError(v *string) *ParseJobUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ParseJobUpdate) SetCreatedAt(v time.Time) *ParseJobUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ParseJobUpdate) SetNillableCreatedAt(v *time.Time) *ParseJobUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ParseJobUpdate) SetUpdatedAt(v time.Time) *ParseJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ParseJobUpdate) SetNillableUpdatedAt(v *time.Time) *ParseJobUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ParseJobMutation object of the builder.
func (_u *ParseJobUpdate) Mutation() *ParseJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ParseJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParseJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ParseJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParseJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParseJobUpdate) check() error {
	if v, ok := _u.mutation.TraceID(); ok {
		if err := parsejob.TraceIDValidator(v); err != nil {
			return &ValidationError{Name: "trace_id", err: fmt.Errorf(`dao: validator failed for field "ParseJob.trace_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := parsejob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`dao: validator failed for field "ParseJob.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ParseJobUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ParseJobUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ParseJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parsejob.Table, parsejob.Columns, sqlgraph.NewFieldSpec(parsejob.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(parsejob.FieldTraceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(parsejob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(parsejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(parsejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(parsejob.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(parsejob.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(parsejob.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.ParseJob
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parsejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ParseJobUpdateOne is the builder for updating a single ParseJob entity.
type ParseJobUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ParseJobMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTraceID sets the "trace_id" field.
func (_u *ParseJobUpdateOne) SetTraceID(v string) *ParseJobUpdateOne {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *ParseJobUpdateOne) SetNillableTraceID(v *string) *ParseJobUpdateOne {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ParseJobUpdateOne) SetStatus(v string) *ParseJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ParseJobUpdateOne) SetNillableStatus(v *string) *ParseJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *ParseJobUpdateOne) SetAttempts(v int) *ParseJobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *ParseJobUpdateOne) SetNillableAttempts(v *int) *ParseJobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *ParseJobUpdateOne) AddAttempts(v int) *ParseJobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ParseJobUpdateOne) SetLastError(v string) *ParseJobUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ParseJobUpdateOne) SetNillableLastError(v *string) *ParseJobUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ParseJobUpdateOne) SetCreatedAt(v time.Time) *ParseJobUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ParseJobUpdateOne) SetNillableCreatedAt(v *time.Time) *ParseJobUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ParseJobUpdateOne) SetUpdatedAt(v time.Time) *ParseJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ParseJobUpdateOne) SetNillableUpdatedAt(v *time.Time) *ParseJobUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ParseJobMutation object of the builder.
func (_u *ParseJobUpdateOne) Mutation() *ParseJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the ParseJobUpdate builder.
func (_u *ParseJobUpdateOne) Where(ps ...predicate.ParseJob) *ParseJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ParseJobUpdateOne) Select(field string, fields ...string) *ParseJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ParseJob entity.
func (_u *ParseJobUpdateOne) Save(ctx context.Context) (*ParseJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParseJobUpdateOne) SaveX(ctx context.Context) *ParseJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ParseJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParseJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParseJobUpdateOne) check() error {
	if v, ok := _u.mutation.TraceID(); ok {
		if err := parsejob.TraceIDValidator(v); err != nil {
			return &ValidationError{Name: "trace_id", err: fmt.Errorf(`dao: validator failed for field "ParseJob.trace_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := parsejob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`dao: validator failed for field "ParseJob.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ParseJobUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ParseJobUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ParseJobUpdateOne) sqlSave(ctx context.Context) (_node *ParseJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parsejob.Table, parsejob.Columns, sqlgraph.NewFieldSpec(parsejob.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`dao: missing "ParseJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, parsejob.FieldID)
		for _, f := range fields {
			if !parsejob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("dao: invalid field %q for query", f)}
			}
			if f != parsejob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(parsejob.FieldTraceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(parsejob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(parsejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(parsejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(parsejob.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(parsejob.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(parsejob.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.ParseJob
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	_node = &ParseJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parsejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
