// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingfs/llm-tracelab/ent/dao/response"
)

// ResponseCreate is the builder for creating a Response entity.
type ResponseCreate struct {
	config
	mutation *ResponseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConversationID sets the "conversation_id" field.
func (_c *ResponseCreate) SetConversationID(v string) *ResponseCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_c *ResponseCreate) SetNillableConversationID(v *string) *ResponseCreate {
	if v != nil {
		_c.SetConversationID(*v)
	}
	return _c
}

// SetPreviousResponseID sets the "previous_response_id" field.
func (_c *ResponseCreate) SetPreviousResponseID(v string) *ResponseCreate {
	_c.mutation.SetPreviousResponseID(v)
	return _c
}

// SetNillablePreviousResponseID sets the "previous_response_id" field if the given value is not nil.
func (_c *ResponseCreate) SetNillablePreviousResponseID(v *string) *ResponseCreate {
	if v != nil {
		_c.SetPreviousResponseID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResponseCreate) SetStatus(v response.Status) *ResponseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResponseCreate) SetNillableStatus(v *response.Status) *ResponseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ResponseCreate) SetModel(v string) *ResponseCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetHistoryItemIds sets the "history_item_ids" field.
func (_c *ResponseCreate) SetHistoryItemIds(v []string) *ResponseCreate {
	_c.mutation.SetHistoryItemIds(v)
	return _c
}

// SetOutputItemIds sets the "output_item_ids" field.
func (_c *ResponseCreate) SetOutputItemIds(v []string) *ResponseCreate {
	_c.mutation.SetOutputItemIds(v)
	return _c
}

// SetEffectiveTools sets the "effective_tools" field.
func (_c *ResponseCreate) SetEffectiveTools(v []map[string]interface{}) *ResponseCreate {
	_c.mutation.SetEffectiveTools(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ResponseCreate) SetMetadata(v map[string]interface{}) *ResponseCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetUsage sets the "usage" field.
func (_c *ResponseCreate) SetUsage(v map[string]interface{}) *ResponseCreate {
	_c.mutation.SetUsage(v)
	return _c
}

// SetError sets the "error" field.
func (_c *ResponseCreate) SetError(v map[string]interface{}) *ResponseCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResponseCreate) SetCreatedAt(v time.Time) *ResponseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResponseCreate) SetNillableCreatedAt(v *time.Time) *ResponseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResponseCreate) SetUpdatedAt(v time.Time) *ResponseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResponseCreate) SetNillableUpdatedAt(v *time.Time) *ResponseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResponseCreate) SetID(v string) *ResponseCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ResponseMutation object of the builder.
func (_c *ResponseCreate) Mutation() *ResponseMutation {
	return _c.mutation
}

// Save creates the Response in the database.
func (_c *ResponseCreate) Save(ctx context.Context) (*Response, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResponseCreate) SaveX(ctx context.Context) *Response {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResponseCreate) defaults() {
	if _, ok := _c.mutation.ConversationID(); !ok {
		v := response.DefaultConversationID
		_c.mutation.SetConversationID(v)
	}
	if _, ok := _c.mutation.PreviousResponseID(); !ok {
		v := response.DefaultPreviousResponseID
		_c.mutation.SetPreviousResponseID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := response.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := response.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := response.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResponseCreate) check() error {
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`dao: missing required field "Response.conversation_id"`)}
	}
	if _, ok := _c.mutation.PreviousResponseID(); !ok {
		return &ValidationError{Name: "previous_response_id", err: errors.New(`dao: missing required field "Response.previous_response_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`dao: missing required field "Response.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := response.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`dao: validator failed for field "Response.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`dao: missing required field "Response.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := response.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`dao: validator failed for field "Response.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`dao: missing required field "Response.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`dao: missing required field "Response.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := response.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`dao: validator failed for field "Response.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ResponseCreate) sqlSave(ctx context.Context) (*Response, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Response.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResponseCreate) createSpec() (*Response, *sqlgraph.CreateSpec) {
	var (
		_node = &Response{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(response.Table, sqlgraph.NewFieldSpec(response.FieldID, field.TypeString))
	)
	_spec.Schema = _c.schemaConfig.Response
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(response.FieldConversationID, field.TypeString, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.PreviousResponseID(); ok {
		_spec.SetField(response.FieldPreviousResponseID, field.TypeString, value)
		_node.PreviousResponseID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(response.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(response.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.HistoryItemIds(); ok {
		_spec.SetField(response.FieldHistoryItemIds, field.TypeJSON, value)
		_node.HistoryItemIds = value
	}
	if value, ok := _c.mutation.OutputItemIds(); ok {
		_spec.SetField(response.FieldOutputItemIds, field.TypeJSON, value)
		_node.OutputItemIds = value
	}
	if value, ok := _c.mutation.EffectiveTools(); ok {
		_spec.SetField(response.FieldEffectiveTools, field.TypeJSON, value)
		_node.EffectiveTools = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(response.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Usage(); ok {
		_spec.SetField(response.FieldUsage, field.TypeJSON, value)
		_node.Usage = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(response.FieldError, field.TypeJSON, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(response.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(response.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Response.Create().
//		SetConversationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResponseUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResponseCreate) OnConflict(opts ...sql.ConflictOption) *ResponseUpsertOne {
	_c.conflict = opts
	return &ResponseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Response.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResponseCreate) OnConflictColumns(columns ...string) *ResponseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResponseUpsertOne{
		create: _c,
	}
}

type (
	// ResponseUpsertOne is the builder for "upsert"-ing
	//  one Response node.
	ResponseUpsertOne struct {
		create *ResponseCreate
	}

	// ResponseUpsert is the "OnConflict" setter.
	ResponseUpsert struct {
		*sql.UpdateSet
	}
)

// SetConversationID sets the "conversation_id" field.
func (u *ResponseUpsert) SetConversationID(v string) *ResponseUpsert {
	u.Set(response.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateConversationID() *ResponseUpsert {
	u.SetExcluded(response.FieldConversationID)
	return u
}

// SetPreviousResponseID sets the "previous_response_id" field.
func (u *ResponseUpsert) SetPreviousResponseID(v string) *ResponseUpsert {
	u.Set(response.FieldPreviousResponseID, v)
	return u
}

// UpdatePreviousResponseID sets the "previous_response_id" field to the value that was provided on create.
func (u *ResponseUpsert) UpdatePreviousResponseID() *ResponseUpsert {
	u.SetExcluded(response.FieldPreviousResponseID)
	return u
}

// SetStatus sets the "status" field.
func (u *ResponseUpsert) SetStatus(v response.Status) *ResponseUpsert {
	u.Set(response.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateStatus() *ResponseUpsert {
	u.SetExcluded(response.FieldStatus)
	return u
}

// SetModel sets the "model" field.
func (u *ResponseUpsert) SetModel(v string) *ResponseUpsert {
	u.Set(response.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateModel() *ResponseUpsert {
	u.SetExcluded(response.FieldModel)
	return u
}

// SetHistoryItemIds sets the "history_item_ids" field.
func (u *ResponseUpsert) SetHistoryItemIds(v []string) *ResponseUpsert {
	u.Set(response.FieldHistoryItemIds, v)
	return u
}

// UpdateHistoryItemIds sets the "history_item_ids" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateHistoryItemIds() *ResponseUpsert {
	u.SetExcluded(response.FieldHistoryItemIds)
	return u
}

// ClearHistoryItemIds clears the value of the "history_item_ids" field.
func (u *ResponseUpsert) ClearHistoryItemIds() *ResponseUpsert {
	u.SetNull(response.FieldHistoryItemIds)
	return u
}

// SetOutputItemIds sets the "output_item_ids" field.
func (u *ResponseUpsert) SetOutputItemIds(v []string) *ResponseUpsert {
	u.Set(response.FieldOutputItemIds, v)
	return u
}

// UpdateOutputItemIds sets the "output_item_ids" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateOutputItemIds() *ResponseUpsert {
	u.SetExcluded(response.FieldOutputItemIds)
	return u
}

// ClearOutputItemIds clears the value of the "output_item_ids" field.
func (u *ResponseUpsert) ClearOutputItemIds() *ResponseUpsert {
	u.SetNull(response.FieldOutputItemIds)
	return u
}

// SetEffectiveTools sets the "effective_tools" field.
func (u *ResponseUpsert) SetEffectiveTools(v []map[string]interface{}) *ResponseUpsert {
	u.Set(response.FieldEffectiveTools, v)
	return u
}

// UpdateEffectiveTools sets the "effective_tools" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateEffectiveTools() *ResponseUpsert {
	u.SetExcluded(response.FieldEffectiveTools)
	return u
}

// ClearEffectiveTools clears the value of the "effective_tools" field.
func (u *ResponseUpsert) ClearEffectiveTools() *ResponseUpsert {
	u.SetNull(response.FieldEffectiveTools)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ResponseUpsert) SetMetadata(v map[string]interface{}) *ResponseUpsert {
	u.Set(response.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateMetadata() *ResponseUpsert {
	u.SetExcluded(response.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ResponseUpsert) ClearMetadata() *ResponseUpsert {
	u.SetNull(response.FieldMetadata)
	return u
}

// SetUsage sets the "usage" field.
func (u *ResponseUpsert) SetUsage(v map[string]interface{}) *ResponseUpsert {
	u.Set(response.FieldUsage, v)
	return u
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateUsage() *ResponseUpsert {
	u.SetExcluded(response.FieldUsage)
	return u
}

// ClearUsage clears the value of the "usage" field.
func (u *ResponseUpsert) ClearUsage() *ResponseUpsert {
	u.SetNull(response.FieldUsage)
	return u
}

// SetError sets the "error" field.
func (u *ResponseUpsert) SetError(v map[string]interface{}) *ResponseUpsert {
	u.Set(response.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateError() *ResponseUpsert {
	u.SetExcluded(response.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *ResponseUpsert) ClearError() *ResponseUpsert {
	u.SetNull(response.FieldError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResponseUpsert) SetUpdatedAt(v time.Time) *ResponseUpsert {
	u.Set(response.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResponseUpsert) UpdateUpdatedAt() *ResponseUpsert {
	u.SetExcluded(response.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Response.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(response.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResponseUpsertOne) UpdateNewValues() *ResponseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(response.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(response.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Response.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResponseUpsertOne) Ignore() *ResponseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResponseUpsertOne) DoNothing() *ResponseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResponseCreate.OnConflict
// documentation for more info.
func (u *ResponseUpsertOne) Update(set func(*ResponseUpsert)) *ResponseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResponseUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ResponseUpsertOne) SetConversationID(v string) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateConversationID() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateConversationID()
	})
}

// SetPreviousResponseID sets the "previous_response_id" field.
func (u *ResponseUpsertOne) SetPreviousResponseID(v string) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetPreviousResponseID(v)
	})
}

// UpdatePreviousResponseID sets the "previous_response_id" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdatePreviousResponseID() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdatePreviousResponseID()
	})
}

// SetStatus sets the "status" field.
func (u *ResponseUpsertOne) SetStatus(v response.Status) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateStatus() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateStatus()
	})
}

// SetModel sets the "model" field.
func (u *ResponseUpsertOne) SetModel(v string) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateModel() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateModel()
	})
}

// SetHistoryItemIds sets the "history_item_ids" field.
func (u *ResponseUpsertOne) SetHistoryItemIds(v []string) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetHistoryItemIds(v)
	})
}

// UpdateHistoryItemIds sets the "history_item_ids" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateHistoryItemIds() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateHistoryItemIds()
	})
}

// ClearHistoryItemIds clears the value of the "history_item_ids" field.
func (u *ResponseUpsertOne) ClearHistoryItemIds() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearHistoryItemIds()
	})
}

// SetOutputItemIds sets the "output_item_ids" field.
func (u *ResponseUpsertOne) SetOutputItemIds(v []string) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetOutputItemIds(v)
	})
}

// UpdateOutputItemIds sets the "output_item_ids" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateOutputItemIds() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateOutputItemIds()
	})
}

// ClearOutputItemIds clears the value of the "output_item_ids" field.
func (u *ResponseUpsertOne) ClearOutputItemIds() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearOutputItemIds()
	})
}

// SetEffectiveTools sets the "effective_tools" field.
func (u *ResponseUpsertOne) SetEffectiveTools(v []map[string]interface{}) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetEffectiveTools(v)
	})
}

// UpdateEffectiveTools sets the "effective_tools" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateEffectiveTools() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateEffectiveTools()
	})
}

// ClearEffectiveTools clears the value of the "effective_tools" field.
func (u *ResponseUpsertOne) ClearEffectiveTools() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearEffectiveTools()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ResponseUpsertOne) SetMetadata(v map[string]interface{}) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateMetadata() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ResponseUpsertOne) ClearMetadata() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearMetadata()
	})
}

// SetUsage sets the "usage" field.
func (u *ResponseUpsertOne) SetUsage(v map[string]interface{}) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetUsage(v)
	})
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateUsage() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateUsage()
	})
}

// ClearUsage clears the value of the "usage" field.
func (u *ResponseUpsertOne) ClearUsage() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearUsage()
	})
}

// SetError sets the "error" field.
func (u *ResponseUpsertOne) SetError(v map[string]interface{}) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateError() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ResponseUpsertOne) ClearError() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResponseUpsertOne) SetUpdatedAt(v time.Time) *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResponseUpsertOne) UpdateUpdatedAt() *ResponseUpsertOne {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ResponseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for ResponseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResponseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResponseUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("dao: ResponseUpsertOne.ID is not supported by MySQL driver. Use ResponseUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResponseUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResponseCreateBulk is the builder for creating many Response entities in bulk.
type ResponseCreateBulk struct {
	config
	err      error
	builders []*ResponseCreate
	conflict []sql.ConflictOption
}

// Save creates the Response entities in the database.
func (_c *ResponseCreateBulk) Save(ctx context.Context) ([]*Response, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Response, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResponseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResponseCreateBulk) SaveX(ctx context.Context) []*Response {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Response.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResponseUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResponseCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResponseUpsertBulk {
	_c.conflict = opts
	return &ResponseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Response.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResponseCreateBulk) OnConflictColumns(columns ...string) *ResponseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResponseUpsertBulk{
		create: _c,
	}
}

// ResponseUpsertBulk is the builder for "upsert"-ing
// a bulk of Response nodes.
type ResponseUpsertBulk struct {
	create *ResponseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Response.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(response.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResponseUpsertBulk) UpdateNewValues() *ResponseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(response.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(response.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Response.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResponseUpsertBulk) Ignore() *ResponseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResponseUpsertBulk) DoNothing() *ResponseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResponseCreateBulk.OnConflict
// documentation for more info.
func (u *ResponseUpsertBulk) Update(set func(*ResponseUpsert)) *ResponseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResponseUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ResponseUpsertBulk) SetConversationID(v string) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateConversationID() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateConversationID()
	})
}

// SetPreviousResponseID sets the "previous_response_id" field.
func (u *ResponseUpsertBulk) SetPreviousResponseID(v string) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetPreviousResponseID(v)
	})
}

// UpdatePreviousResponseID sets the "previous_response_id" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdatePreviousResponseID() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdatePreviousResponseID()
	})
}

// SetStatus sets the "status" field.
func (u *ResponseUpsertBulk) SetStatus(v response.Status) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateStatus() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateStatus()
	})
}

// SetModel sets the "model" field.
func (u *ResponseUpsertBulk) SetModel(v string) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateModel() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateModel()
	})
}

// SetHistoryItemIds sets the "history_item_ids" field.
func (u *ResponseUpsertBulk) SetHistoryItemIds(v []string) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetHistoryItemIds(v)
	})
}

// UpdateHistoryItemIds sets the "history_item_ids" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateHistoryItemIds() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateHistoryItemIds()
	})
}

// ClearHistoryItemIds clears the value of the "history_item_ids" field.
func (u *ResponseUpsertBulk) ClearHistoryItemIds() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearHistoryItemIds()
	})
}

// SetOutputItemIds sets the "output_item_ids" field.
func (u *ResponseUpsertBulk) SetOutputItemIds(v []string) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetOutputItemIds(v)
	})
}

// UpdateOutputItemIds sets the "output_item_ids" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateOutputItemIds() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateOutputItemIds()
	})
}

// ClearOutputItemIds clears the value of the "output_item_ids" field.
func (u *ResponseUpsertBulk) ClearOutputItemIds() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearOutputItemIds()
	})
}

// SetEffectiveTools sets the "effective_tools" field.
func (u *ResponseUpsertBulk) SetEffectiveTools(v []map[string]interface{}) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetEffectiveTools(v)
	})
}

// UpdateEffectiveTools sets the "effective_tools" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateEffectiveTools() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateEffectiveTools()
	})
}

// ClearEffectiveTools clears the value of the "effective_tools" field.
func (u *ResponseUpsertBulk) ClearEffectiveTools() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearEffectiveTools()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ResponseUpsertBulk) SetMetadata(v map[string]interface{}) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateMetadata() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ResponseUpsertBulk) ClearMetadata() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearMetadata()
	})
}

// SetUsage sets the "usage" field.
func (u *ResponseUpsertBulk) SetUsage(v map[string]interface{}) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetUsage(v)
	})
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateUsage() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateUsage()
	})
}

// ClearUsage clears the value of the "usage" field.
func (u *ResponseUpsertBulk) ClearUsage() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearUsage()
	})
}

// SetError sets the "error" field.
func (u *ResponseUpsertBulk) SetError(v map[string]interface{}) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateError() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ResponseUpsertBulk) ClearError() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.ClearError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResponseUpsertBulk) SetUpdatedAt(v time.Time) *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResponseUpsertBulk) UpdateUpdatedAt() *ResponseUpsertBulk {
	return u.Update(func(s *ResponseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ResponseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("dao: OnConflict was set for builder %d. Set it on the ResponseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for ResponseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResponseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
