// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingfs/llm-tracelab/ent/dao/internal"
	"github.com/kingfs/llm-tracelab/ent/dao/predicate"
	"github.com/kingfs/llm-tracelab/ent/dao/score"
)

// ScoreUpdate is the builder for updating Score entities.
type ScoreUpdate struct {
	config
	hooks     []Hook
	mutation  *ScoreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ScoreUpdate builder.
func (_u *ScoreUpdate) Where(ps ...predicate.Score) *ScoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTraceID sets the "trace_id" field.
func (_u *ScoreUpdate) SetTraceID(v string) *ScoreUpdate {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableTraceID(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ScoreUpdate) SetSessionID(v string) *ScoreUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableSessionID(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetDatasetID sets the "dataset_id" field.
func (_u *ScoreUpdate) SetDatasetID(v string) *ScoreUpdate {
	_u.mutation.SetDatasetID(v)
	return _u
}

// SetNillableDatasetID sets the "dataset_id" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableDatasetID(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetDatasetID(*v)
	}
	return _u
}

// SetEvalRunID sets the "eval_run_id" field.
func (_u *ScoreUpdate) SetEvalRunID(v string) *ScoreUpdate {
	_u.mutation.SetEvalRunID(v)
	return _u
}

// SetNillableEvalRunID sets the "eval_run_id" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableEvalRunID(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetEvalRunID(*v)
	}
	return _u
}

// SetEvaluatorKey sets the "evaluator_key" field.
func (_u *ScoreUpdate) SetEvaluatorKey(v string) *ScoreUpdate {
	_u.mutation.SetEvaluatorKey(v)
	return _u
}

// SetNillableEvaluatorKey sets the "evaluator_key" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableEvaluatorKey(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetEvaluatorKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ScoreUpdate) SetValue(v float64) *ScoreUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableValue(v *float64) *ScoreUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *ScoreUpdate) AddValue(v float64) *ScoreUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScoreUpdate) SetStatus(v string) *ScoreUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableStatus(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *ScoreUpdate) SetLabel(v string) *ScoreUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableLabel(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetExplanation sets the "explanation" field.
func (_u *ScoreUpdate) SetExplanation(v string) *ScoreUpdate {
	_u.mutation.SetExplanation(v)
	return _u
}

// SetNillableExplanation sets the "explanation" field if the given value is not nil.
func (_u *ScoreUpdate) SetNillableExplanation(v *string) *ScoreUpdate {
	if v != nil {
		_u.SetExplanation(*v)
	}
	return _u
}

// Mutation returns the ScoreMutation object of the builder.
func (_u *ScoreUpdate) Mutation() *ScoreMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScoreUpdate) check() error {
	if v, ok := _u.mutation.TraceID(); ok {
		if err := score.TraceIDValidator(v); err != nil {
			return &ValidationError{Name: "trace_id", err: fmt.Errorf(`dao: validator failed for field "Score.trace_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EvaluatorKey(); ok {
		if err := score.EvaluatorKeyValidator(v); err != nil {
			return &ValidationError{Name: "evaluator_key", err: fmt.Errorf(`dao: validator failed for field "Score.evaluator_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ScoreUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ScoreUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ScoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(score.Table, score.Columns, sqlgraph.NewFieldSpec(score.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(score.FieldTraceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(score.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DatasetID(); ok {
		_spec.SetField(score.FieldDatasetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvalRunID(); ok {
		_spec.SetField(score.FieldEvalRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvaluatorKey(); ok {
		_spec.SetField(score.FieldEvaluatorKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(score.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(score.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(score.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(score.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Explanation(); ok {
		_spec.SetField(score.FieldExplanation, field.TypeString, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Score
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{score.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScoreUpdateOne is the builder for updating a single Score entity.
type ScoreUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ScoreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTraceID sets the "trace_id" field.
func (_u *ScoreUpdateOne) SetTraceID(v string) *ScoreUpdateOne {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableTraceID(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ScoreUpdateOne) SetSessionID(v string) *ScoreUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableSessionID(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetDatasetID sets the "dataset_id" field.
func (_u *ScoreUpdateOne) SetDatasetID(v string) *ScoreUpdateOne {
	_u.mutation.SetDatasetID(v)
	return _u
}

// SetNillableDatasetID sets the "dataset_id" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableDatasetID(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetDatasetID(*v)
	}
	return _u
}

// SetEvalRunID sets the "eval_run_id" field.
func (_u *ScoreUpdateOne) SetEvalRunID(v string) *ScoreUpdateOne {
	_u.mutation.SetEvalRunID(v)
	return _u
}

// SetNillableEvalRunID sets the "eval_run_id" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableEvalRunID(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetEvalRunID(*v)
	}
	return _u
}

// SetEvaluatorKey sets the "evaluator_key" field.
func (_u *ScoreUpdateOne) SetEvaluatorKey(v string) *ScoreUpdateOne {
	_u.mutation.SetEvaluatorKey(v)
	return _u
}

// SetNillableEvaluatorKey sets the "evaluator_key" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableEvaluatorKey(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetEvaluatorKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ScoreUpdateOne) SetValue(v float64) *ScoreUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableValue(v *float64) *ScoreUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *ScoreUpdateOne) AddValue(v float64) *ScoreUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScoreUpdateOne) SetStatus(v string) *ScoreUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableStatus(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *ScoreUpdateOne) SetLabel(v string) *ScoreUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableLabel(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetExplanation sets the "explanation" field.
func (_u *ScoreUpdateOne) SetExplanation(v string) *ScoreUpdateOne {
	_u.mutation.SetExplanation(v)
	return _u
}

// SetNillableExplanation sets the "explanation" field if the given value is not nil.
func (_u *ScoreUpdateOne) SetNillableExplanation(v *string) *ScoreUpdateOne {
	if v != nil {
		_u.SetExplanation(*v)
	}
	return _u
}

// Mutation returns the ScoreMutation object of the builder.
func (_u *ScoreUpdateOne) Mutation() *ScoreMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScoreUpdate builder.
func (_u *ScoreUpdateOne) Where(ps ...predicate.Score) *ScoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScoreUpdateOne) Select(field string, fields ...string) *ScoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Score entity.
func (_u *ScoreUpdateOne) Save(ctx context.Context) (*Score, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScoreUpdateOne) SaveX(ctx context.Context) *Score {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScoreUpdateOne) check() error {
	if v, ok := _u.mutation.TraceID(); ok {
		if err := score.TraceIDValidator(v); err != nil {
			return &ValidationError{Name: "trace_id", err: fmt.Errorf(`dao: validator failed for field "Score.trace_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EvaluatorKey(); ok {
		if err := score.EvaluatorKeyValidator(v); err != nil {
			return &ValidationError{Name: "evaluator_key", err: fmt.Errorf(`dao: validator failed for field "Score.evaluator_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ScoreUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ScoreUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ScoreUpdateOne) sqlSave(ctx context.Context) (_node *Score, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(score.Table, score.Columns, sqlgraph.NewFieldSpec(score.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`dao: missing "Score.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, score.FieldID)
		for _, f := range fields {
			if !score.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("dao: invalid field %q for query", f)}
			}
			if f != score.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(score.FieldTraceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(score.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DatasetID(); ok {
		_spec.SetField(score.FieldDatasetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvalRunID(); ok {
		_spec.SetField(score.FieldEvalRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvaluatorKey(); ok {
		_spec.SetField(score.FieldEvaluatorKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(score.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(score.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(score.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(score.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Explanation(); ok {
		_spec.SetField(score.FieldExplanation, field.TypeString, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Score
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	_node = &Score{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{score.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
