// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingfs/llm-tracelab/ent/dao/toolcallaudit"
)

// ToolCallAuditCreate is the builder for creating a ToolCallAudit entity.
type ToolCallAuditCreate struct {
	config
	mutation *ToolCallAuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResponseID sets the "response_id" field.
func (_c *ToolCallAuditCreate) SetResponseID(v string) *ToolCallAuditCreate {
	_c.mutation.SetResponseID(v)
	return _c
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableResponseID(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetResponseID(*v)
	}
	return _c
}

// SetRequestAuditID sets the "request_audit_id" field.
func (_c *ToolCallAuditCreate) SetRequestAuditID(v string) *ToolCallAuditCreate {
	_c.mutation.SetRequestAuditID(v)
	return _c
}

// SetNillableRequestAuditID sets the "request_audit_id" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableRequestAuditID(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetRequestAuditID(*v)
	}
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *ToolCallAuditCreate) SetConversationID(v string) *ToolCallAuditCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableConversationID(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetConversationID(*v)
	}
	return _c
}

// SetCallID sets the "call_id" field.
func (_c *ToolCallAuditCreate) SetCallID(v string) *ToolCallAuditCreate {
	_c.mutation.SetCallID(v)
	return _c
}

// SetToolType sets the "tool_type" field.
func (_c *ToolCallAuditCreate) SetToolType(v string) *ToolCallAuditCreate {
	_c.mutation.SetToolType(v)
	return _c
}

// SetToolName sets the "tool_name" field.
func (_c *ToolCallAuditCreate) SetToolName(v string) *ToolCallAuditCreate {
	_c.mutation.SetToolName(v)
	return _c
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableToolName(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetToolName(*v)
	}
	return _c
}

// SetExecutor sets the "executor" field.
func (_c *ToolCallAuditCreate) SetExecutor(v string) *ToolCallAuditCreate {
	_c.mutation.SetExecutor(v)
	return _c
}

// SetNillableExecutor sets the "executor" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableExecutor(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetExecutor(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ToolCallAuditCreate) SetStatus(v string) *ToolCallAuditCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableStatus(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *ToolCallAuditCreate) SetPhase(v string) *ToolCallAuditCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillablePhase(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetInputJSON sets the "input_json" field.
func (_c *ToolCallAuditCreate) SetInputJSON(v map[string]interface{}) *ToolCallAuditCreate {
	_c.mutation.SetInputJSON(v)
	return _c
}

// SetOutputJSON sets the "output_json" field.
func (_c *ToolCallAuditCreate) SetOutputJSON(v map[string]interface{}) *ToolCallAuditCreate {
	_c.mutation.SetOutputJSON(v)
	return _c
}

// SetErrorText sets the "error_text" field.
func (_c *ToolCallAuditCreate) SetErrorText(v string) *ToolCallAuditCreate {
	_c.mutation.SetErrorText(v)
	return _c
}

// SetNillableErrorText sets the "error_text" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableErrorText(v *string) *ToolCallAuditCreate {
	if v != nil {
		_c.SetErrorText(*v)
	}
	return _c
}

// SetMetadataJSON sets the "metadata_json" field.
func (_c *ToolCallAuditCreate) SetMetadataJSON(v map[string]interface{}) *ToolCallAuditCreate {
	_c.mutation.SetMetadataJSON(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ToolCallAuditCreate) SetStartedAt(v time.Time) *ToolCallAuditCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableStartedAt(v *time.Time) *ToolCallAuditCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ToolCallAuditCreate) SetCompletedAt(v time.Time) *ToolCallAuditCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableCompletedAt(v *time.Time) *ToolCallAuditCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ToolCallAuditCreate) SetCreatedAt(v time.Time) *ToolCallAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ToolCallAuditCreate) SetNillableCreatedAt(v *time.Time) *ToolCallAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ToolCallAuditCreate) SetID(v string) *ToolCallAuditCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ToolCallAuditMutation object of the builder.
func (_c *ToolCallAuditCreate) Mutation() *ToolCallAuditMutation {
	return _c.mutation
}

// Save creates the ToolCallAudit in the database.
func (_c *ToolCallAuditCreate) Save(ctx context.Context) (*ToolCallAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ToolCallAuditCreate) SaveX(ctx context.Context) *ToolCallAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolCallAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolCallAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ToolCallAuditCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := toolcallaudit.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Phase(); !ok {
		v := toolcallaudit.DefaultPhase
		_c.mutation.SetPhase(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := toolcallaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ToolCallAuditCreate) check() error {
	if _, ok := _c.mutation.CallID(); !ok {
		return &ValidationError{Name: "call_id", err: errors.New(`dao: missing required field "ToolCallAudit.call_id"`)}
	}
	if v, ok := _c.mutation.CallID(); ok {
		if err := toolcallaudit.CallIDValidator(v); err != nil {
			return &ValidationError{Name: "call_id", err: fmt.Errorf(`dao: validator failed for field "ToolCallAudit.call_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToolType(); !ok {
		return &ValidationError{Name: "tool_type", err: errors.New(`dao: missing required field "ToolCallAudit.tool_type"`)}
	}
	if v, ok := _c.mutation.ToolType(); ok {
		if err := toolcallaudit.ToolTypeValidator(v); err != nil {
			return &ValidationError{Name: "tool_type", err: fmt.Errorf(`dao: validator failed for field "ToolCallAudit.tool_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`dao: missing required field "ToolCallAudit.status"`)}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`dao: missing required field "ToolCallAudit.phase"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`dao: missing required field "ToolCallAudit.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := toolcallaudit.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`dao: validator failed for field "ToolCallAudit.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ToolCallAuditCreate) sqlSave(ctx context.Context) (*ToolCallAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ToolCallAudit.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ToolCallAuditCreate) createSpec() (*ToolCallAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &ToolCallAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(toolcallaudit.Table, sqlgraph.NewFieldSpec(toolcallaudit.FieldID, field.TypeString))
	)
	_spec.Schema = _c.schemaConfig.ToolCallAudit
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ResponseID(); ok {
		_spec.SetField(toolcallaudit.FieldResponseID, field.TypeString, value)
		_node.ResponseID = value
	}
	if value, ok := _c.mutation.RequestAuditID(); ok {
		_spec.SetField(toolcallaudit.FieldRequestAuditID, field.TypeString, value)
		_node.RequestAuditID = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(toolcallaudit.FieldConversationID, field.TypeString, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.CallID(); ok {
		_spec.SetField(toolcallaudit.FieldCallID, field.TypeString, value)
		_node.CallID = value
	}
	if value, ok := _c.mutation.ToolType(); ok {
		_spec.SetField(toolcallaudit.FieldToolType, field.TypeString, value)
		_node.ToolType = value
	}
	if value, ok := _c.mutation.ToolName(); ok {
		_spec.SetField(toolcallaudit.FieldToolName, field.TypeString, value)
		_node.ToolName = value
	}
	if value, ok := _c.mutation.Executor(); ok {
		_spec.SetField(toolcallaudit.FieldExecutor, field.TypeString, value)
		_node.Executor = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(toolcallaudit.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(toolcallaudit.FieldPhase, field.TypeString, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.InputJSON(); ok {
		_spec.SetField(toolcallaudit.FieldInputJSON, field.TypeJSON, value)
		_node.InputJSON = value
	}
	if value, ok := _c.mutation.OutputJSON(); ok {
		_spec.SetField(toolcallaudit.FieldOutputJSON, field.TypeJSON, value)
		_node.OutputJSON = value
	}
	if value, ok := _c.mutation.ErrorText(); ok {
		_spec.SetField(toolcallaudit.FieldErrorText, field.TypeString, value)
		_node.ErrorText = value
	}
	if value, ok := _c.mutation.MetadataJSON(); ok {
		_spec.SetField(toolcallaudit.FieldMetadataJSON, field.TypeJSON, value)
		_node.MetadataJSON = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(toolcallaudit.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(toolcallaudit.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(toolcallaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ToolCallAudit.Create().
//		SetResponseID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ToolCallAuditUpsert) {
//			SetResponseID(v+v).
//		}).
//		Exec(ctx)
func (_c *ToolCallAuditCreate) OnConflict(opts ...sql.ConflictOption) *ToolCallAuditUpsertOne {
	_c.conflict = opts
	return &ToolCallAuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ToolCallAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ToolCallAuditCreate) OnConflictColumns(columns ...string) *ToolCallAuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ToolCallAuditUpsertOne{
		create: _c,
	}
}

type (
	// ToolCallAuditUpsertOne is the builder for "upsert"-ing
	//  one ToolCallAudit node.
	ToolCallAuditUpsertOne struct {
		create *ToolCallAuditCreate
	}

	// ToolCallAuditUpsert is the "OnConflict" setter.
	ToolCallAuditUpsert struct {
		*sql.UpdateSet
	}
)

// SetResponseID sets the "response_id" field.
func (u *ToolCallAuditUpsert) SetResponseID(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldResponseID, v)
	return u
}

// UpdateResponseID sets the "response_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateResponseID() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldResponseID)
	return u
}

// ClearResponseID clears the value of the "response_id" field.
func (u *ToolCallAuditUpsert) ClearResponseID() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldResponseID)
	return u
}

// SetRequestAuditID sets the "request_audit_id" field.
func (u *ToolCallAuditUpsert) SetRequestAuditID(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldRequestAuditID, v)
	return u
}

// UpdateRequestAuditID sets the "request_audit_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateRequestAuditID() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldRequestAuditID)
	return u
}

// ClearRequestAuditID clears the value of the "request_audit_id" field.
func (u *ToolCallAuditUpsert) ClearRequestAuditID() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldRequestAuditID)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ToolCallAuditUpsert) SetConversationID(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateConversationID() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldConversationID)
	return u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ToolCallAuditUpsert) ClearConversationID() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldConversationID)
	return u
}

// SetCallID sets the "call_id" field.
func (u *ToolCallAuditUpsert) SetCallID(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldCallID, v)
	return u
}

// UpdateCallID sets the "call_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateCallID() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldCallID)
	return u
}

// SetToolType sets the "tool_type" field.
func (u *ToolCallAuditUpsert) SetToolType(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldToolType, v)
	return u
}

// UpdateToolType sets the "tool_type" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateToolType() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldToolType)
	return u
}

// SetToolName sets the "tool_name" field.
func (u *ToolCallAuditUpsert) SetToolName(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldToolName, v)
	return u
}

// UpdateToolName sets the "tool_name" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateToolName() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldToolName)
	return u
}

// ClearToolName clears the value of the "tool_name" field.
func (u *ToolCallAuditUpsert) ClearToolName() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldToolName)
	return u
}

// SetExecutor sets the "executor" field.
func (u *ToolCallAuditUpsert) SetExecutor(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldExecutor, v)
	return u
}

// UpdateExecutor sets the "executor" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateExecutor() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldExecutor)
	return u
}

// ClearExecutor clears the value of the "executor" field.
func (u *ToolCallAuditUpsert) ClearExecutor() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldExecutor)
	return u
}

// SetStatus sets the "status" field.
func (u *ToolCallAuditUpsert) SetStatus(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateStatus() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldStatus)
	return u
}

// SetPhase sets the "phase" field.
func (u *ToolCallAuditUpsert) SetPhase(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldPhase, v)
	return u
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdatePhase() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldPhase)
	return u
}

// SetInputJSON sets the "input_json" field.
func (u *ToolCallAuditUpsert) SetInputJSON(v map[string]interface{}) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldInputJSON, v)
	return u
}

// UpdateInputJSON sets the "input_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateInputJSON() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldInputJSON)
	return u
}

// ClearInputJSON clears the value of the "input_json" field.
func (u *ToolCallAuditUpsert) ClearInputJSON() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldInputJSON)
	return u
}

// SetOutputJSON sets the "output_json" field.
func (u *ToolCallAuditUpsert) SetOutputJSON(v map[string]interface{}) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldOutputJSON, v)
	return u
}

// UpdateOutputJSON sets the "output_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateOutputJSON() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldOutputJSON)
	return u
}

// ClearOutputJSON clears the value of the "output_json" field.
func (u *ToolCallAuditUpsert) ClearOutputJSON() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldOutputJSON)
	return u
}

// SetErrorText sets the "error_text" field.
func (u *ToolCallAuditUpsert) SetErrorText(v string) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldErrorText, v)
	return u
}

// UpdateErrorText sets the "error_text" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateErrorText() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldErrorText)
	return u
}

// ClearErrorText clears the value of the "error_text" field.
func (u *ToolCallAuditUpsert) ClearErrorText() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldErrorText)
	return u
}

// SetMetadataJSON sets the "metadata_json" field.
func (u *ToolCallAuditUpsert) SetMetadataJSON(v map[string]interface{}) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldMetadataJSON, v)
	return u
}

// UpdateMetadataJSON sets the "metadata_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateMetadataJSON() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldMetadataJSON)
	return u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (u *ToolCallAuditUpsert) ClearMetadataJSON() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldMetadataJSON)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *ToolCallAuditUpsert) SetStartedAt(v time.Time) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateStartedAt() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ToolCallAuditUpsert) ClearStartedAt() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *ToolCallAuditUpsert) SetCompletedAt(v time.Time) *ToolCallAuditUpsert {
	u.Set(toolcallaudit.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ToolCallAuditUpsert) UpdateCompletedAt() *ToolCallAuditUpsert {
	u.SetExcluded(toolcallaudit.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ToolCallAuditUpsert) ClearCompletedAt() *ToolCallAuditUpsert {
	u.SetNull(toolcallaudit.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ToolCallAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(toolcallaudit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ToolCallAuditUpsertOne) UpdateNewValues() *ToolCallAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(toolcallaudit.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(toolcallaudit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ToolCallAudit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ToolCallAuditUpsertOne) Ignore() *ToolCallAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ToolCallAuditUpsertOne) DoNothing() *ToolCallAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ToolCallAuditCreate.OnConflict
// documentation for more info.
func (u *ToolCallAuditUpsertOne) Update(set func(*ToolCallAuditUpsert)) *ToolCallAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ToolCallAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetResponseID sets the "response_id" field.
func (u *ToolCallAuditUpsertOne) SetResponseID(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetResponseID(v)
	})
}

// UpdateResponseID sets the "response_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateResponseID() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateResponseID()
	})
}

// ClearResponseID clears the value of the "response_id" field.
func (u *ToolCallAuditUpsertOne) ClearResponseID() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearResponseID()
	})
}

// SetRequestAuditID sets the "request_audit_id" field.
func (u *ToolCallAuditUpsertOne) SetRequestAuditID(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetRequestAuditID(v)
	})
}

// UpdateRequestAuditID sets the "request_audit_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateRequestAuditID() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateRequestAuditID()
	})
}

// ClearRequestAuditID clears the value of the "request_audit_id" field.
func (u *ToolCallAuditUpsertOne) ClearRequestAuditID() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearRequestAuditID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ToolCallAuditUpsertOne) SetConversationID(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateConversationID() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ToolCallAuditUpsertOne) ClearConversationID() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearConversationID()
	})
}

// SetCallID sets the "call_id" field.
func (u *ToolCallAuditUpsertOne) SetCallID(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetCallID(v)
	})
}

// UpdateCallID sets the "call_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateCallID() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateCallID()
	})
}

// SetToolType sets the "tool_type" field.
func (u *ToolCallAuditUpsertOne) SetToolType(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetToolType(v)
	})
}

// UpdateToolType sets the "tool_type" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateToolType() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateToolType()
	})
}

// SetToolName sets the "tool_name" field.
func (u *ToolCallAuditUpsertOne) SetToolName(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetToolName(v)
	})
}

// UpdateToolName sets the "tool_name" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateToolName() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateToolName()
	})
}

// ClearToolName clears the value of the "tool_name" field.
func (u *ToolCallAuditUpsertOne) ClearToolName() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearToolName()
	})
}

// SetExecutor sets the "executor" field.
func (u *ToolCallAuditUpsertOne) SetExecutor(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetExecutor(v)
	})
}

// UpdateExecutor sets the "executor" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateExecutor() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateExecutor()
	})
}

// ClearExecutor clears the value of the "executor" field.
func (u *ToolCallAuditUpsertOne) ClearExecutor() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearExecutor()
	})
}

// SetStatus sets the "status" field.
func (u *ToolCallAuditUpsertOne) SetStatus(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateStatus() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateStatus()
	})
}

// SetPhase sets the "phase" field.
func (u *ToolCallAuditUpsertOne) SetPhase(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdatePhase() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdatePhase()
	})
}

// SetInputJSON sets the "input_json" field.
func (u *ToolCallAuditUpsertOne) SetInputJSON(v map[string]interface{}) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetInputJSON(v)
	})
}

// UpdateInputJSON sets the "input_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateInputJSON() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateInputJSON()
	})
}

// ClearInputJSON clears the value of the "input_json" field.
func (u *ToolCallAuditUpsertOne) ClearInputJSON() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearInputJSON()
	})
}

// SetOutputJSON sets the "output_json" field.
func (u *ToolCallAuditUpsertOne) SetOutputJSON(v map[string]interface{}) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetOutputJSON(v)
	})
}

// UpdateOutputJSON sets the "output_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateOutputJSON() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateOutputJSON()
	})
}

// ClearOutputJSON clears the value of the "output_json" field.
func (u *ToolCallAuditUpsertOne) ClearOutputJSON() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearOutputJSON()
	})
}

// SetErrorText sets the "error_text" field.
func (u *ToolCallAuditUpsertOne) SetErrorText(v string) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetErrorText(v)
	})
}

// UpdateErrorText sets the "error_text" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateErrorText() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateErrorText()
	})
}

// ClearErrorText clears the value of the "error_text" field.
func (u *ToolCallAuditUpsertOne) ClearErrorText() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearErrorText()
	})
}

// SetMetadataJSON sets the "metadata_json" field.
func (u *ToolCallAuditUpsertOne) SetMetadataJSON(v map[string]interface{}) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetMetadataJSON(v)
	})
}

// UpdateMetadataJSON sets the "metadata_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateMetadataJSON() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateMetadataJSON()
	})
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (u *ToolCallAuditUpsertOne) ClearMetadataJSON() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearMetadataJSON()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ToolCallAuditUpsertOne) SetStartedAt(v time.Time) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateStartedAt() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ToolCallAuditUpsertOne) ClearStartedAt() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ToolCallAuditUpsertOne) SetCompletedAt(v time.Time) *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ToolCallAuditUpsertOne) UpdateCompletedAt() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ToolCallAuditUpsertOne) ClearCompletedAt() *ToolCallAuditUpsertOne {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *ToolCallAuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for ToolCallAuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ToolCallAuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ToolCallAuditUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("dao: ToolCallAuditUpsertOne.ID is not supported by MySQL driver. Use ToolCallAuditUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ToolCallAuditUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ToolCallAuditCreateBulk is the builder for creating many ToolCallAudit entities in bulk.
type ToolCallAuditCreateBulk struct {
	config
	err      error
	builders []*ToolCallAuditCreate
	conflict []sql.ConflictOption
}

// Save creates the ToolCallAudit entities in the database.
func (_c *ToolCallAuditCreateBulk) Save(ctx context.Context) ([]*ToolCallAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ToolCallAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToolCallAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ToolCallAuditCreateBulk) SaveX(ctx context.Context) []*ToolCallAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolCallAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolCallAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ToolCallAudit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ToolCallAuditUpsert) {
//			SetResponseID(v+v).
//		}).
//		Exec(ctx)
func (_c *ToolCallAuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *ToolCallAuditUpsertBulk {
	_c.conflict = opts
	return &ToolCallAuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ToolCallAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ToolCallAuditCreateBulk) OnConflictColumns(columns ...string) *ToolCallAuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ToolCallAuditUpsertBulk{
		create: _c,
	}
}

// ToolCallAuditUpsertBulk is the builder for "upsert"-ing
// a bulk of ToolCallAudit nodes.
type ToolCallAuditUpsertBulk struct {
	create *ToolCallAuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ToolCallAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(toolcallaudit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ToolCallAuditUpsertBulk) UpdateNewValues() *ToolCallAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(toolcallaudit.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(toolcallaudit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ToolCallAudit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ToolCallAuditUpsertBulk) Ignore() *ToolCallAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ToolCallAuditUpsertBulk) DoNothing() *ToolCallAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ToolCallAuditCreateBulk.OnConflict
// documentation for more info.
func (u *ToolCallAuditUpsertBulk) Update(set func(*ToolCallAuditUpsert)) *ToolCallAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ToolCallAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetResponseID sets the "response_id" field.
func (u *ToolCallAuditUpsertBulk) SetResponseID(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetResponseID(v)
	})
}

// UpdateResponseID sets the "response_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateResponseID() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateResponseID()
	})
}

// ClearResponseID clears the value of the "response_id" field.
func (u *ToolCallAuditUpsertBulk) ClearResponseID() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearResponseID()
	})
}

// SetRequestAuditID sets the "request_audit_id" field.
func (u *ToolCallAuditUpsertBulk) SetRequestAuditID(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetRequestAuditID(v)
	})
}

// UpdateRequestAuditID sets the "request_audit_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateRequestAuditID() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateRequestAuditID()
	})
}

// ClearRequestAuditID clears the value of the "request_audit_id" field.
func (u *ToolCallAuditUpsertBulk) ClearRequestAuditID() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearRequestAuditID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ToolCallAuditUpsertBulk) SetConversationID(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateConversationID() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ToolCallAuditUpsertBulk) ClearConversationID() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearConversationID()
	})
}

// SetCallID sets the "call_id" field.
func (u *ToolCallAuditUpsertBulk) SetCallID(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetCallID(v)
	})
}

// UpdateCallID sets the "call_id" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateCallID() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateCallID()
	})
}

// SetToolType sets the "tool_type" field.
func (u *ToolCallAuditUpsertBulk) SetToolType(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetToolType(v)
	})
}

// UpdateToolType sets the "tool_type" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateToolType() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateToolType()
	})
}

// SetToolName sets the "tool_name" field.
func (u *ToolCallAuditUpsertBulk) SetToolName(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetToolName(v)
	})
}

// UpdateToolName sets the "tool_name" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateToolName() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateToolName()
	})
}

// ClearToolName clears the value of the "tool_name" field.
func (u *ToolCallAuditUpsertBulk) ClearToolName() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearToolName()
	})
}

// SetExecutor sets the "executor" field.
func (u *ToolCallAuditUpsertBulk) SetExecutor(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetExecutor(v)
	})
}

// UpdateExecutor sets the "executor" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateExecutor() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateExecutor()
	})
}

// ClearExecutor clears the value of the "executor" field.
func (u *ToolCallAuditUpsertBulk) ClearExecutor() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearExecutor()
	})
}

// SetStatus sets the "status" field.
func (u *ToolCallAuditUpsertBulk) SetStatus(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateStatus() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateStatus()
	})
}

// SetPhase sets the "phase" field.
func (u *ToolCallAuditUpsertBulk) SetPhase(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdatePhase() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdatePhase()
	})
}

// SetInputJSON sets the "input_json" field.
func (u *ToolCallAuditUpsertBulk) SetInputJSON(v map[string]interface{}) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetInputJSON(v)
	})
}

// UpdateInputJSON sets the "input_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateInputJSON() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateInputJSON()
	})
}

// ClearInputJSON clears the value of the "input_json" field.
func (u *ToolCallAuditUpsertBulk) ClearInputJSON() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearInputJSON()
	})
}

// SetOutputJSON sets the "output_json" field.
func (u *ToolCallAuditUpsertBulk) SetOutputJSON(v map[string]interface{}) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetOutputJSON(v)
	})
}

// UpdateOutputJSON sets the "output_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateOutputJSON() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateOutputJSON()
	})
}

// ClearOutputJSON clears the value of the "output_json" field.
func (u *ToolCallAuditUpsertBulk) ClearOutputJSON() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearOutputJSON()
	})
}

// SetErrorText sets the "error_text" field.
func (u *ToolCallAuditUpsertBulk) SetErrorText(v string) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetErrorText(v)
	})
}

// UpdateErrorText sets the "error_text" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateErrorText() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateErrorText()
	})
}

// ClearErrorText clears the value of the "error_text" field.
func (u *ToolCallAuditUpsertBulk) ClearErrorText() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearErrorText()
	})
}

// SetMetadataJSON sets the "metadata_json" field.
func (u *ToolCallAuditUpsertBulk) SetMetadataJSON(v map[string]interface{}) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetMetadataJSON(v)
	})
}

// UpdateMetadataJSON sets the "metadata_json" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateMetadataJSON() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateMetadataJSON()
	})
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (u *ToolCallAuditUpsertBulk) ClearMetadataJSON() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearMetadataJSON()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ToolCallAuditUpsertBulk) SetStartedAt(v time.Time) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateStartedAt() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ToolCallAuditUpsertBulk) ClearStartedAt() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ToolCallAuditUpsertBulk) SetCompletedAt(v time.Time) *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ToolCallAuditUpsertBulk) UpdateCompletedAt() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ToolCallAuditUpsertBulk) ClearCompletedAt() *ToolCallAuditUpsertBulk {
	return u.Update(func(s *ToolCallAuditUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *ToolCallAuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("dao: OnConflict was set for builder %d. Set it on the ToolCallAuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for ToolCallAuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ToolCallAuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
