// Code generated by ent, DO NOT EDIT.

package dao

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kingfs/llm-tracelab/ent/dao/upstreamexchange"
)

// UpstreamExchange is the model entity for the UpstreamExchange schema.
type UpstreamExchange struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ResponseID holds the value of the "response_id" field.
	ResponseID string `json:"response_id,omitempty"`
	// RequestAuditID holds the value of the "request_audit_id" field.
	RequestAuditID string `json:"request_audit_id,omitempty"`
	// TraceID holds the value of the "trace_id" field.
	TraceID string `json:"trace_id,omitempty"`
	// ExchangeID holds the value of the "exchange_id" field.
	ExchangeID string `json:"exchange_id,omitempty"`
	// ExchangeKind holds the value of the "exchange_kind" field.
	ExchangeKind string `json:"exchange_kind,omitempty"`
	// ExchangeRole holds the value of the "exchange_role" field.
	ExchangeRole string `json:"exchange_role,omitempty"`
	// ParentExchangeID holds the value of the "parent_exchange_id" field.
	ParentExchangeID string `json:"parent_exchange_id,omitempty"`
	// SequenceIndex holds the value of the "sequence_index" field.
	SequenceIndex int `json:"sequence_index,omitempty"`
	// CassettePath holds the value of the "cassette_path" field.
	CassettePath string `json:"cassette_path,omitempty"`
	// UpstreamID holds the value of the "upstream_id" field.
	UpstreamID string `json:"upstream_id,omitempty"`
	// RouteTarget holds the value of the "route_target" field.
	RouteTarget string `json:"route_target,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode int `json:"status_code,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// ErrorText holds the value of the "error_text" field.
	ErrorText    string `json:"error_text,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamExchange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamexchange.FieldSequenceIndex, upstreamexchange.FieldStatusCode:
			values[i] = new(sql.NullInt64)
		case upstreamexchange.FieldID, upstreamexchange.FieldResponseID, upstreamexchange.FieldRequestAuditID, upstreamexchange.FieldTraceID, upstreamexchange.FieldExchangeID, upstreamexchange.FieldExchangeKind, upstreamexchange.FieldExchangeRole, upstreamexchange.FieldParentExchangeID, upstreamexchange.FieldCassettePath, upstreamexchange.FieldUpstreamID, upstreamexchange.FieldRouteTarget, upstreamexchange.FieldModel, upstreamexchange.FieldEndpoint, upstreamexchange.FieldErrorText:
			values[i] = new(sql.NullString)
		case upstreamexchange.FieldStartedAt, upstreamexchange.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamExchange fields.
func (_m *UpstreamExchange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamexchange.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case upstreamexchange.FieldResponseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_id", values[i])
			} else if value.Valid {
				_m.ResponseID = value.String
			}
		case upstreamexchange.FieldRequestAuditID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_audit_id", values[i])
			} else if value.Valid {
				_m.RequestAuditID = value.String
			}
		case upstreamexchange.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				_m.TraceID = value.String
			}
		case upstreamexchange.FieldExchangeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_id", values[i])
			} else if value.Valid {
				_m.ExchangeID = value.String
			}
		case upstreamexchange.FieldExchangeKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_kind", values[i])
			} else if value.Valid {
				_m.ExchangeKind = value.String
			}
		case upstreamexchange.FieldExchangeRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_role", values[i])
			} else if value.Valid {
				_m.ExchangeRole = value.String
			}
		case upstreamexchange.FieldParentExchangeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_exchange_id", values[i])
			} else if value.Valid {
				_m.ParentExchangeID = value.String
			}
		case upstreamexchange.FieldSequenceIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence_index", values[i])
			} else if value.Valid {
				_m.SequenceIndex = int(value.Int64)
			}
		case upstreamexchange.FieldCassettePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cassette_path", values[i])
			} else if value.Valid {
				_m.CassettePath = value.String
			}
		case upstreamexchange.FieldUpstreamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_id", values[i])
			} else if value.Valid {
				_m.UpstreamID = value.String
			}
		case upstreamexchange.FieldRouteTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_target", values[i])
			} else if value.Valid {
				_m.RouteTarget = value.String
			}
		case upstreamexchange.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case upstreamexchange.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case upstreamexchange.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = int(value.Int64)
			}
		case upstreamexchange.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case upstreamexchange.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		case upstreamexchange.FieldErrorText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_text", values[i])
			} else if value.Valid {
				_m.ErrorText = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamExchange.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamExchange) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamExchange.
// Note that you need to call UpstreamExchange.Unwrap() before calling this method if this UpstreamExchange
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamExchange) Update() *UpstreamExchangeUpdateOne {
	return NewUpstreamExchangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamExchange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamExchange) Unwrap() *UpstreamExchange {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("dao: UpstreamExchange is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamExchange) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamExchange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("response_id=")
	builder.WriteString(_m.ResponseID)
	builder.WriteString(", ")
	builder.WriteString("request_audit_id=")
	builder.WriteString(_m.RequestAuditID)
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(_m.TraceID)
	builder.WriteString(", ")
	builder.WriteString("exchange_id=")
	builder.WriteString(_m.ExchangeID)
	builder.WriteString(", ")
	builder.WriteString("exchange_kind=")
	builder.WriteString(_m.ExchangeKind)
	builder.WriteString(", ")
	builder.WriteString("exchange_role=")
	builder.WriteString(_m.ExchangeRole)
	builder.WriteString(", ")
	builder.WriteString("parent_exchange_id=")
	builder.WriteString(_m.ParentExchangeID)
	builder.WriteString(", ")
	builder.WriteString("sequence_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.SequenceIndex))
	builder.WriteString(", ")
	builder.WriteString("cassette_path=")
	builder.WriteString(_m.CassettePath)
	builder.WriteString(", ")
	builder.WriteString("upstream_id=")
	builder.WriteString(_m.UpstreamID)
	builder.WriteString(", ")
	builder.WriteString("route_target=")
	builder.WriteString(_m.RouteTarget)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("error_text=")
	builder.WriteString(_m.ErrorText)
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamExchanges is a parsable slice of UpstreamExchange.
type UpstreamExchanges []*UpstreamExchange
