// Code generated by ent, DO NOT EDIT.

package dao

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kingfs/llm-tracelab/ent/dao/upstreammodel"
)

// UpstreamModel is the model entity for the UpstreamModel schema.
type UpstreamModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UpstreamID holds the value of the "upstream_id" field.
	UpstreamID string `json:"upstream_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SeenAt holds the value of the "seen_at" field.
	SeenAt       time.Time `json:"seen_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreammodel.FieldID:
			values[i] = new(sql.NullInt64)
		case upstreammodel.FieldUpstreamID, upstreammodel.FieldModel, upstreammodel.FieldSource:
			values[i] = new(sql.NullString)
		case upstreammodel.FieldSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamModel fields.
func (_m *UpstreamModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreammodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case upstreammodel.FieldUpstreamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_id", values[i])
			} else if value.Valid {
				_m.UpstreamID = value.String
			}
		case upstreammodel.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case upstreammodel.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case upstreammodel.FieldSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field seen_at", values[i])
			} else if value.Valid {
				_m.SeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamModel.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamModel.
// Note that you need to call UpstreamModel.Unwrap() before calling this method if this UpstreamModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamModel) Update() *UpstreamModelUpdateOne {
	return NewUpstreamModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamModel) Unwrap() *UpstreamModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("dao: UpstreamModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamModel) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upstream_id=")
	builder.WriteString(_m.UpstreamID)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("seen_at=")
	builder.WriteString(_m.SeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamModels is a parsable slice of UpstreamModel.
type UpstreamModels []*UpstreamModel
