// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingfs/llm-tracelab/ent/dao/upstreammodel"
)

// UpstreamModelCreate is the builder for creating a UpstreamModel entity.
type UpstreamModelCreate struct {
	config
	mutation *UpstreamModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUpstreamID sets the "upstream_id" field.
func (_c *UpstreamModelCreate) SetUpstreamID(v string) *UpstreamModelCreate {
	_c.mutation.SetUpstreamID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *UpstreamModelCreate) SetModel(v string) *UpstreamModelCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *UpstreamModelCreate) SetSource(v string) *UpstreamModelCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *UpstreamModelCreate) SetNillableSource(v *string) *UpstreamModelCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSeenAt sets the "seen_at" field.
func (_c *UpstreamModelCreate) SetSeenAt(v time.Time) *UpstreamModelCreate {
	_c.mutation.SetSeenAt(v)
	return _c
}

// SetNillableSeenAt sets the "seen_at" field if the given value is not nil.
func (_c *UpstreamModelCreate) SetNillableSeenAt(v *time.Time) *UpstreamModelCreate {
	if v != nil {
		_c.SetSeenAt(*v)
	}
	return _c
}

// Mutation returns the UpstreamModelMutation object of the builder.
func (_c *UpstreamModelCreate) Mutation() *UpstreamModelMutation {
	return _c.mutation
}

// Save creates the UpstreamModel in the database.
func (_c *UpstreamModelCreate) Save(ctx context.Context) (*UpstreamModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamModelCreate) SaveX(ctx context.Context) *UpstreamModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamModelCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := upstreammodel.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.SeenAt(); !ok {
		v := upstreammodel.DefaultSeenAt()
		_c.mutation.SetSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamModelCreate) check() error {
	if _, ok := _c.mutation.UpstreamID(); !ok {
		return &ValidationError{Name: "upstream_id", err: errors.New(`dao: missing required field "UpstreamModel.upstream_id"`)}
	}
	if v, ok := _c.mutation.UpstreamID(); ok {
		if err := upstreammodel.UpstreamIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_id", err: fmt.Errorf(`dao: validator failed for field "UpstreamModel.upstream_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`dao: missing required field "UpstreamModel.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := upstreammodel.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`dao: validator failed for field "UpstreamModel.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`dao: missing required field "UpstreamModel.source"`)}
	}
	if _, ok := _c.mutation.SeenAt(); !ok {
		return &ValidationError{Name: "seen_at", err: errors.New(`dao: missing required field "UpstreamModel.seen_at"`)}
	}
	return nil
}

func (_c *UpstreamModelCreate) sqlSave(ctx context.Context) (*UpstreamModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamModelCreate) createSpec() (*UpstreamModel, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreammodel.Table, sqlgraph.NewFieldSpec(upstreammodel.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.UpstreamModel
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UpstreamID(); ok {
		_spec.SetField(upstreammodel.FieldUpstreamID, field.TypeString, value)
		_node.UpstreamID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(upstreammodel.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(upstreammodel.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SeenAt(); ok {
		_spec.SetField(upstreammodel.FieldSeenAt, field.TypeTime, value)
		_node.SeenAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamModel.Create().
//		SetUpstreamID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamModelUpsert) {
//			SetUpstreamID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamModelCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamModelUpsertOne {
	_c.conflict = opts
	return &UpstreamModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamModelCreate) OnConflictColumns(columns ...string) *UpstreamModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamModelUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamModelUpsertOne is the builder for "upsert"-ing
	//  one UpstreamModel node.
	UpstreamModelUpsertOne struct {
		create *UpstreamModelCreate
	}

	// UpstreamModelUpsert is the "OnConflict" setter.
	UpstreamModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpstreamID sets the "upstream_id" field.
func (u *UpstreamModelUpsert) SetUpstreamID(v string) *UpstreamModelUpsert {
	u.Set(upstreammodel.FieldUpstreamID, v)
	return u
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UpstreamModelUpsert) UpdateUpstreamID() *UpstreamModelUpsert {
	u.SetExcluded(upstreammodel.FieldUpstreamID)
	return u
}

// SetModel sets the "model" field.
func (u *UpstreamModelUpsert) SetModel(v string) *UpstreamModelUpsert {
	u.Set(upstreammodel.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UpstreamModelUpsert) UpdateModel() *UpstreamModelUpsert {
	u.SetExcluded(upstreammodel.FieldModel)
	return u
}

// SetSource sets the "source" field.
func (u *UpstreamModelUpsert) SetSource(v string) *UpstreamModelUpsert {
	u.Set(upstreammodel.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UpstreamModelUpsert) UpdateSource() *UpstreamModelUpsert {
	u.SetExcluded(upstreammodel.FieldSource)
	return u
}

// SetSeenAt sets the "seen_at" field.
func (u *UpstreamModelUpsert) SetSeenAt(v time.Time) *UpstreamModelUpsert {
	u.Set(upstreammodel.FieldSeenAt, v)
	return u
}

// UpdateSeenAt sets the "seen_at" field to the value that was provided on create.
func (u *UpstreamModelUpsert) UpdateSeenAt() *UpstreamModelUpsert {
	u.SetExcluded(upstreammodel.FieldSeenAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamModelUpsertOne) UpdateNewValues() *UpstreamModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamModelUpsertOne) Ignore() *UpstreamModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamModelUpsertOne) DoNothing() *UpstreamModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamModelCreate.OnConflict
// documentation for more info.
func (u *UpstreamModelUpsertOne) Update(set func(*UpstreamModelUpsert)) *UpstreamModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UpstreamModelUpsertOne) SetUpstreamID(v string) *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetUpstreamID(v)
	})
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UpstreamModelUpsertOne) UpdateUpstreamID() *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateUpstreamID()
	})
}

// SetModel sets the "model" field.
func (u *UpstreamModelUpsertOne) SetModel(v string) *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UpstreamModelUpsertOne) UpdateModel() *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateModel()
	})
}

// SetSource sets the "source" field.
func (u *UpstreamModelUpsertOne) SetSource(v string) *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UpstreamModelUpsertOne) UpdateSource() *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateSource()
	})
}

// SetSeenAt sets the "seen_at" field.
func (u *UpstreamModelUpsertOne) SetSeenAt(v time.Time) *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetSeenAt(v)
	})
}

// UpdateSeenAt sets the "seen_at" field to the value that was provided on create.
func (u *UpstreamModelUpsertOne) UpdateSeenAt() *UpstreamModelUpsertOne {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateSeenAt()
	})
}

// Exec executes the query.
func (u *UpstreamModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for UpstreamModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamModelUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamModelUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamModelCreateBulk is the builder for creating many UpstreamModel entities in bulk.
type UpstreamModelCreateBulk struct {
	config
	err      error
	builders []*UpstreamModelCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamModel entities in the database.
func (_c *UpstreamModelCreateBulk) Save(ctx context.Context) ([]*UpstreamModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamModelCreateBulk) SaveX(ctx context.Context) []*UpstreamModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamModelUpsert) {
//			SetUpstreamID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamModelUpsertBulk {
	_c.conflict = opts
	return &UpstreamModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamModelCreateBulk) OnConflictColumns(columns ...string) *UpstreamModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamModelUpsertBulk{
		create: _c,
	}
}

// UpstreamModelUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamModel nodes.
type UpstreamModelUpsertBulk struct {
	create *UpstreamModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamModelUpsertBulk) UpdateNewValues() *UpstreamModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamModelUpsertBulk) Ignore() *UpstreamModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamModelUpsertBulk) DoNothing() *UpstreamModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamModelCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamModelUpsertBulk) Update(set func(*UpstreamModelUpsert)) *UpstreamModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UpstreamModelUpsertBulk) SetUpstreamID(v string) *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetUpstreamID(v)
	})
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UpstreamModelUpsertBulk) UpdateUpstreamID() *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateUpstreamID()
	})
}

// SetModel sets the "model" field.
func (u *UpstreamModelUpsertBulk) SetModel(v string) *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UpstreamModelUpsertBulk) UpdateModel() *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateModel()
	})
}

// SetSource sets the "source" field.
func (u *UpstreamModelUpsertBulk) SetSource(v string) *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UpstreamModelUpsertBulk) UpdateSource() *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateSource()
	})
}

// SetSeenAt sets the "seen_at" field.
func (u *UpstreamModelUpsertBulk) SetSeenAt(v time.Time) *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.SetSeenAt(v)
	})
}

// UpdateSeenAt sets the "seen_at" field to the value that was provided on create.
func (u *UpstreamModelUpsertBulk) UpdateSeenAt() *UpstreamModelUpsertBulk {
	return u.Update(func(s *UpstreamModelUpsert) {
		s.UpdateSeenAt()
	})
}

// Exec executes the query.
func (u *UpstreamModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("dao: OnConflict was set for builder %d. Set it on the UpstreamModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("dao: missing options for UpstreamModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
