// Code generated by ent, DO NOT EDIT.

package tracelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kingfs/llm-tracelab/ent/dao/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldID, id))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldTraceID, v))
}

// ModTimeNs applies equality check predicate on the "mod_time_ns" field. It's identical to ModTimeNsEQ.
func ModTimeNs(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldModTimeNs, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldFileSize, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldVersion, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRequestID, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRecordedAt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldModel, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldProvider, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldOperation, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldEndpoint, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldURL, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldMethod, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldDurationMs, v))
}

// TtftMs applies equality check predicate on the "ttft_ms" field. It's identical to TtftMsEQ.
func TtftMs(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldTtftMs, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldClientIP, v))
}

// ContentLength applies equality check predicate on the "content_length" field. It's identical to ContentLengthEQ.
func ContentLength(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldContentLength, v))
}

// ErrorText applies equality check predicate on the "error_text" field. It's identical to ErrorTextEQ.
func ErrorText(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldErrorText, v))
}

// PromptTokens applies equality check predicate on the "prompt_tokens" field. It's identical to PromptTokensEQ.
func PromptTokens(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldPromptTokens, v))
}

// CompletionTokens applies equality check predicate on the "completion_tokens" field. It's identical to CompletionTokensEQ.
func CompletionTokens(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldCompletionTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldTotalTokens, v))
}

// CachedTokens applies equality check predicate on the "cached_tokens" field. It's identical to CachedTokensEQ.
func CachedTokens(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldCachedTokens, v))
}

// ReqHeaderLen applies equality check predicate on the "req_header_len" field. It's identical to ReqHeaderLenEQ.
func ReqHeaderLen(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldReqHeaderLen, v))
}

// ReqBodyLen applies equality check predicate on the "req_body_len" field. It's identical to ReqBodyLenEQ.
func ReqBodyLen(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldReqBodyLen, v))
}

// ResHeaderLen applies equality check predicate on the "res_header_len" field. It's identical to ResHeaderLenEQ.
func ResHeaderLen(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldResHeaderLen, v))
}

// ResBodyLen applies equality check predicate on the "res_body_len" field. It's identical to ResBodyLenEQ.
func ResBodyLen(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldResBodyLen, v))
}

// IsStream applies equality check predicate on the "is_stream" field. It's identical to IsStreamEQ.
func IsStream(v bool) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldIsStream, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSessionID, v))
}

// SessionSource applies equality check predicate on the "session_source" field. It's identical to SessionSourceEQ.
func SessionSource(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSessionSource, v))
}

// WindowID applies equality check predicate on the "window_id" field. It's identical to WindowIDEQ.
func WindowID(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldWindowID, v))
}

// ClientRequestID applies equality check predicate on the "client_request_id" field. It's identical to ClientRequestIDEQ.
func ClientRequestID(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldClientRequestID, v))
}

// SelectedUpstreamID applies equality check predicate on the "selected_upstream_id" field. It's identical to SelectedUpstreamIDEQ.
func SelectedUpstreamID(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamBaseURL applies equality check predicate on the "selected_upstream_base_url" field. It's identical to SelectedUpstreamBaseURLEQ.
func SelectedUpstreamBaseURL(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamProviderPreset applies equality check predicate on the "selected_upstream_provider_preset" field. It's identical to SelectedUpstreamProviderPresetEQ.
func SelectedUpstreamProviderPreset(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSelectedUpstreamProviderPreset, v))
}

// RoutingPolicy applies equality check predicate on the "routing_policy" field. It's identical to RoutingPolicyEQ.
func RoutingPolicy(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingPolicy, v))
}

// RoutingScore applies equality check predicate on the "routing_score" field. It's identical to RoutingScoreEQ.
func RoutingScore(v float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingScore, v))
}

// RoutingCandidateCount applies equality check predicate on the "routing_candidate_count" field. It's identical to RoutingCandidateCountEQ.
func RoutingCandidateCount(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingCandidateCount, v))
}

// RoutingFailureReason applies equality check predicate on the "routing_failure_reason" field. It's identical to RoutingFailureReasonEQ.
func RoutingFailureReason(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingFailureReason, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldTraceID, v))
}

// ModTimeNsEQ applies the EQ predicate on the "mod_time_ns" field.
func ModTimeNsEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldModTimeNs, v))
}

// ModTimeNsNEQ applies the NEQ predicate on the "mod_time_ns" field.
func ModTimeNsNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldModTimeNs, v))
}

// ModTimeNsIn applies the In predicate on the "mod_time_ns" field.
func ModTimeNsIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldModTimeNs, vs...))
}

// ModTimeNsNotIn applies the NotIn predicate on the "mod_time_ns" field.
func ModTimeNsNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldModTimeNs, vs...))
}

// ModTimeNsGT applies the GT predicate on the "mod_time_ns" field.
func ModTimeNsGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldModTimeNs, v))
}

// ModTimeNsGTE applies the GTE predicate on the "mod_time_ns" field.
func ModTimeNsGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldModTimeNs, v))
}

// ModTimeNsLT applies the LT predicate on the "mod_time_ns" field.
func ModTimeNsLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldModTimeNs, v))
}

// ModTimeNsLTE applies the LTE predicate on the "mod_time_ns" field.
func ModTimeNsLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldModTimeNs, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldFileSize, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldVersion, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldRequestID, v))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldRecordedAt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldModel, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldProvider, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldOperation, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldEndpoint, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldURL, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldMethod, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldStatusCode, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldDurationMs, v))
}

// TtftMsEQ applies the EQ predicate on the "ttft_ms" field.
func TtftMsEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldTtftMs, v))
}

// TtftMsNEQ applies the NEQ predicate on the "ttft_ms" field.
func TtftMsNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldTtftMs, v))
}

// TtftMsIn applies the In predicate on the "ttft_ms" field.
func TtftMsIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldTtftMs, vs...))
}

// TtftMsNotIn applies the NotIn predicate on the "ttft_ms" field.
func TtftMsNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldTtftMs, vs...))
}

// TtftMsGT applies the GT predicate on the "ttft_ms" field.
func TtftMsGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldTtftMs, v))
}

// TtftMsGTE applies the GTE predicate on the "ttft_ms" field.
func TtftMsGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldTtftMs, v))
}

// TtftMsLT applies the LT predicate on the "ttft_ms" field.
func TtftMsLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldTtftMs, v))
}

// TtftMsLTE applies the LTE predicate on the "ttft_ms" field.
func TtftMsLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldTtftMs, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldClientIP, v))
}

// ContentLengthEQ applies the EQ predicate on the "content_length" field.
func ContentLengthEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldContentLength, v))
}

// ContentLengthNEQ applies the NEQ predicate on the "content_length" field.
func ContentLengthNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldContentLength, v))
}

// ContentLengthIn applies the In predicate on the "content_length" field.
func ContentLengthIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldContentLength, vs...))
}

// ContentLengthNotIn applies the NotIn predicate on the "content_length" field.
func ContentLengthNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldContentLength, vs...))
}

// ContentLengthGT applies the GT predicate on the "content_length" field.
func ContentLengthGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldContentLength, v))
}

// ContentLengthGTE applies the GTE predicate on the "content_length" field.
func ContentLengthGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldContentLength, v))
}

// ContentLengthLT applies the LT predicate on the "content_length" field.
func ContentLengthLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldContentLength, v))
}

// ContentLengthLTE applies the LTE predicate on the "content_length" field.
func ContentLengthLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldContentLength, v))
}

// ErrorTextEQ applies the EQ predicate on the "error_text" field.
func ErrorTextEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldErrorText, v))
}

// ErrorTextNEQ applies the NEQ predicate on the "error_text" field.
func ErrorTextNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldErrorText, v))
}

// ErrorTextIn applies the In predicate on the "error_text" field.
func ErrorTextIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldErrorText, vs...))
}

// ErrorTextNotIn applies the NotIn predicate on the "error_text" field.
func ErrorTextNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldErrorText, vs...))
}

// ErrorTextGT applies the GT predicate on the "error_text" field.
func ErrorTextGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldErrorText, v))
}

// ErrorTextGTE applies the GTE predicate on the "error_text" field.
func ErrorTextGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldErrorText, v))
}

// ErrorTextLT applies the LT predicate on the "error_text" field.
func ErrorTextLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldErrorText, v))
}

// ErrorTextLTE applies the LTE predicate on the "error_text" field.
func ErrorTextLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldErrorText, v))
}

// ErrorTextContains applies the Contains predicate on the "error_text" field.
func ErrorTextContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldErrorText, v))
}

// ErrorTextHasPrefix applies the HasPrefix predicate on the "error_text" field.
func ErrorTextHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldErrorText, v))
}

// ErrorTextHasSuffix applies the HasSuffix predicate on the "error_text" field.
func ErrorTextHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldErrorText, v))
}

// ErrorTextEqualFold applies the EqualFold predicate on the "error_text" field.
func ErrorTextEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldErrorText, v))
}

// ErrorTextContainsFold applies the ContainsFold predicate on the "error_text" field.
func ErrorTextContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldErrorText, v))
}

// PromptTokensEQ applies the EQ predicate on the "prompt_tokens" field.
func PromptTokensEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldPromptTokens, v))
}

// PromptTokensNEQ applies the NEQ predicate on the "prompt_tokens" field.
func PromptTokensNEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldPromptTokens, v))
}

// PromptTokensIn applies the In predicate on the "prompt_tokens" field.
func PromptTokensIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldPromptTokens, vs...))
}

// PromptTokensNotIn applies the NotIn predicate on the "prompt_tokens" field.
func PromptTokensNotIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldPromptTokens, vs...))
}

// PromptTokensGT applies the GT predicate on the "prompt_tokens" field.
func PromptTokensGT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldPromptTokens, v))
}

// PromptTokensGTE applies the GTE predicate on the "prompt_tokens" field.
func PromptTokensGTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldPromptTokens, v))
}

// PromptTokensLT applies the LT predicate on the "prompt_tokens" field.
func PromptTokensLT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldPromptTokens, v))
}

// PromptTokensLTE applies the LTE predicate on the "prompt_tokens" field.
func PromptTokensLTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldPromptTokens, v))
}

// CompletionTokensEQ applies the EQ predicate on the "completion_tokens" field.
func CompletionTokensEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldCompletionTokens, v))
}

// CompletionTokensNEQ applies the NEQ predicate on the "completion_tokens" field.
func CompletionTokensNEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldCompletionTokens, v))
}

// CompletionTokensIn applies the In predicate on the "completion_tokens" field.
func CompletionTokensIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldCompletionTokens, vs...))
}

// CompletionTokensNotIn applies the NotIn predicate on the "completion_tokens" field.
func CompletionTokensNotIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldCompletionTokens, vs...))
}

// CompletionTokensGT applies the GT predicate on the "completion_tokens" field.
func CompletionTokensGT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldCompletionTokens, v))
}

// CompletionTokensGTE applies the GTE predicate on the "completion_tokens" field.
func CompletionTokensGTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldCompletionTokens, v))
}

// CompletionTokensLT applies the LT predicate on the "completion_tokens" field.
func CompletionTokensLT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldCompletionTokens, v))
}

// CompletionTokensLTE applies the LTE predicate on the "completion_tokens" field.
func CompletionTokensLTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldCompletionTokens, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldTotalTokens, v))
}

// CachedTokensEQ applies the EQ predicate on the "cached_tokens" field.
func CachedTokensEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldCachedTokens, v))
}

// CachedTokensNEQ applies the NEQ predicate on the "cached_tokens" field.
func CachedTokensNEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldCachedTokens, v))
}

// CachedTokensIn applies the In predicate on the "cached_tokens" field.
func CachedTokensIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldCachedTokens, vs...))
}

// CachedTokensNotIn applies the NotIn predicate on the "cached_tokens" field.
func CachedTokensNotIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldCachedTokens, vs...))
}

// CachedTokensGT applies the GT predicate on the "cached_tokens" field.
func CachedTokensGT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldCachedTokens, v))
}

// CachedTokensGTE applies the GTE predicate on the "cached_tokens" field.
func CachedTokensGTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldCachedTokens, v))
}

// CachedTokensLT applies the LT predicate on the "cached_tokens" field.
func CachedTokensLT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldCachedTokens, v))
}

// CachedTokensLTE applies the LTE predicate on the "cached_tokens" field.
func CachedTokensLTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldCachedTokens, v))
}

// ReqHeaderLenEQ applies the EQ predicate on the "req_header_len" field.
func ReqHeaderLenEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldReqHeaderLen, v))
}

// ReqHeaderLenNEQ applies the NEQ predicate on the "req_header_len" field.
func ReqHeaderLenNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldReqHeaderLen, v))
}

// ReqHeaderLenIn applies the In predicate on the "req_header_len" field.
func ReqHeaderLenIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldReqHeaderLen, vs...))
}

// ReqHeaderLenNotIn applies the NotIn predicate on the "req_header_len" field.
func ReqHeaderLenNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldReqHeaderLen, vs...))
}

// ReqHeaderLenGT applies the GT predicate on the "req_header_len" field.
func ReqHeaderLenGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldReqHeaderLen, v))
}

// ReqHeaderLenGTE applies the GTE predicate on the "req_header_len" field.
func ReqHeaderLenGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldReqHeaderLen, v))
}

// ReqHeaderLenLT applies the LT predicate on the "req_header_len" field.
func ReqHeaderLenLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldReqHeaderLen, v))
}

// ReqHeaderLenLTE applies the LTE predicate on the "req_header_len" field.
func ReqHeaderLenLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldReqHeaderLen, v))
}

// ReqBodyLenEQ applies the EQ predicate on the "req_body_len" field.
func ReqBodyLenEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldReqBodyLen, v))
}

// ReqBodyLenNEQ applies the NEQ predicate on the "req_body_len" field.
func ReqBodyLenNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldReqBodyLen, v))
}

// ReqBodyLenIn applies the In predicate on the "req_body_len" field.
func ReqBodyLenIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldReqBodyLen, vs...))
}

// ReqBodyLenNotIn applies the NotIn predicate on the "req_body_len" field.
func ReqBodyLenNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldReqBodyLen, vs...))
}

// ReqBodyLenGT applies the GT predicate on the "req_body_len" field.
func ReqBodyLenGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldReqBodyLen, v))
}

// ReqBodyLenGTE applies the GTE predicate on the "req_body_len" field.
func ReqBodyLenGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldReqBodyLen, v))
}

// ReqBodyLenLT applies the LT predicate on the "req_body_len" field.
func ReqBodyLenLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldReqBodyLen, v))
}

// ReqBodyLenLTE applies the LTE predicate on the "req_body_len" field.
func ReqBodyLenLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldReqBodyLen, v))
}

// ResHeaderLenEQ applies the EQ predicate on the "res_header_len" field.
func ResHeaderLenEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldResHeaderLen, v))
}

// ResHeaderLenNEQ applies the NEQ predicate on the "res_header_len" field.
func ResHeaderLenNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldResHeaderLen, v))
}

// ResHeaderLenIn applies the In predicate on the "res_header_len" field.
func ResHeaderLenIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldResHeaderLen, vs...))
}

// ResHeaderLenNotIn applies the NotIn predicate on the "res_header_len" field.
func ResHeaderLenNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldResHeaderLen, vs...))
}

// ResHeaderLenGT applies the GT predicate on the "res_header_len" field.
func ResHeaderLenGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldResHeaderLen, v))
}

// ResHeaderLenGTE applies the GTE predicate on the "res_header_len" field.
func ResHeaderLenGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldResHeaderLen, v))
}

// ResHeaderLenLT applies the LT predicate on the "res_header_len" field.
func ResHeaderLenLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldResHeaderLen, v))
}

// ResHeaderLenLTE applies the LTE predicate on the "res_header_len" field.
func ResHeaderLenLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldResHeaderLen, v))
}

// ResBodyLenEQ applies the EQ predicate on the "res_body_len" field.
func ResBodyLenEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldResBodyLen, v))
}

// ResBodyLenNEQ applies the NEQ predicate on the "res_body_len" field.
func ResBodyLenNEQ(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldResBodyLen, v))
}

// ResBodyLenIn applies the In predicate on the "res_body_len" field.
func ResBodyLenIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldResBodyLen, vs...))
}

// ResBodyLenNotIn applies the NotIn predicate on the "res_body_len" field.
func ResBodyLenNotIn(vs ...int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldResBodyLen, vs...))
}

// ResBodyLenGT applies the GT predicate on the "res_body_len" field.
func ResBodyLenGT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldResBodyLen, v))
}

// ResBodyLenGTE applies the GTE predicate on the "res_body_len" field.
func ResBodyLenGTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldResBodyLen, v))
}

// ResBodyLenLT applies the LT predicate on the "res_body_len" field.
func ResBodyLenLT(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldResBodyLen, v))
}

// ResBodyLenLTE applies the LTE predicate on the "res_body_len" field.
func ResBodyLenLTE(v int64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldResBodyLen, v))
}

// IsStreamEQ applies the EQ predicate on the "is_stream" field.
func IsStreamEQ(v bool) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldIsStream, v))
}

// IsStreamNEQ applies the NEQ predicate on the "is_stream" field.
func IsStreamNEQ(v bool) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldIsStream, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldSessionID, v))
}

// SessionSourceEQ applies the EQ predicate on the "session_source" field.
func SessionSourceEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSessionSource, v))
}

// SessionSourceNEQ applies the NEQ predicate on the "session_source" field.
func SessionSourceNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldSessionSource, v))
}

// SessionSourceIn applies the In predicate on the "session_source" field.
func SessionSourceIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldSessionSource, vs...))
}

// SessionSourceNotIn applies the NotIn predicate on the "session_source" field.
func SessionSourceNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldSessionSource, vs...))
}

// SessionSourceGT applies the GT predicate on the "session_source" field.
func SessionSourceGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldSessionSource, v))
}

// SessionSourceGTE applies the GTE predicate on the "session_source" field.
func SessionSourceGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldSessionSource, v))
}

// SessionSourceLT applies the LT predicate on the "session_source" field.
func SessionSourceLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldSessionSource, v))
}

// SessionSourceLTE applies the LTE predicate on the "session_source" field.
func SessionSourceLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldSessionSource, v))
}

// SessionSourceContains applies the Contains predicate on the "session_source" field.
func SessionSourceContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldSessionSource, v))
}

// SessionSourceHasPrefix applies the HasPrefix predicate on the "session_source" field.
func SessionSourceHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldSessionSource, v))
}

// SessionSourceHasSuffix applies the HasSuffix predicate on the "session_source" field.
func SessionSourceHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldSessionSource, v))
}

// SessionSourceEqualFold applies the EqualFold predicate on the "session_source" field.
func SessionSourceEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldSessionSource, v))
}

// SessionSourceContainsFold applies the ContainsFold predicate on the "session_source" field.
func SessionSourceContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldSessionSource, v))
}

// WindowIDEQ applies the EQ predicate on the "window_id" field.
func WindowIDEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldWindowID, v))
}

// WindowIDNEQ applies the NEQ predicate on the "window_id" field.
func WindowIDNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldWindowID, v))
}

// WindowIDIn applies the In predicate on the "window_id" field.
func WindowIDIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldWindowID, vs...))
}

// WindowIDNotIn applies the NotIn predicate on the "window_id" field.
func WindowIDNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldWindowID, vs...))
}

// WindowIDGT applies the GT predicate on the "window_id" field.
func WindowIDGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldWindowID, v))
}

// WindowIDGTE applies the GTE predicate on the "window_id" field.
func WindowIDGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldWindowID, v))
}

// WindowIDLT applies the LT predicate on the "window_id" field.
func WindowIDLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldWindowID, v))
}

// WindowIDLTE applies the LTE predicate on the "window_id" field.
func WindowIDLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldWindowID, v))
}

// WindowIDContains applies the Contains predicate on the "window_id" field.
func WindowIDContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldWindowID, v))
}

// WindowIDHasPrefix applies the HasPrefix predicate on the "window_id" field.
func WindowIDHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldWindowID, v))
}

// WindowIDHasSuffix applies the HasSuffix predicate on the "window_id" field.
func WindowIDHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldWindowID, v))
}

// WindowIDEqualFold applies the EqualFold predicate on the "window_id" field.
func WindowIDEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldWindowID, v))
}

// WindowIDContainsFold applies the ContainsFold predicate on the "window_id" field.
func WindowIDContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldWindowID, v))
}

// ClientRequestIDEQ applies the EQ predicate on the "client_request_id" field.
func ClientRequestIDEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldClientRequestID, v))
}

// ClientRequestIDNEQ applies the NEQ predicate on the "client_request_id" field.
func ClientRequestIDNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldClientRequestID, v))
}

// ClientRequestIDIn applies the In predicate on the "client_request_id" field.
func ClientRequestIDIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldClientRequestID, vs...))
}

// ClientRequestIDNotIn applies the NotIn predicate on the "client_request_id" field.
func ClientRequestIDNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldClientRequestID, vs...))
}

// ClientRequestIDGT applies the GT predicate on the "client_request_id" field.
func ClientRequestIDGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldClientRequestID, v))
}

// ClientRequestIDGTE applies the GTE predicate on the "client_request_id" field.
func ClientRequestIDGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldClientRequestID, v))
}

// ClientRequestIDLT applies the LT predicate on the "client_request_id" field.
func ClientRequestIDLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldClientRequestID, v))
}

// ClientRequestIDLTE applies the LTE predicate on the "client_request_id" field.
func ClientRequestIDLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldClientRequestID, v))
}

// ClientRequestIDContains applies the Contains predicate on the "client_request_id" field.
func ClientRequestIDContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldClientRequestID, v))
}

// ClientRequestIDHasPrefix applies the HasPrefix predicate on the "client_request_id" field.
func ClientRequestIDHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldClientRequestID, v))
}

// ClientRequestIDHasSuffix applies the HasSuffix predicate on the "client_request_id" field.
func ClientRequestIDHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldClientRequestID, v))
}

// ClientRequestIDEqualFold applies the EqualFold predicate on the "client_request_id" field.
func ClientRequestIDEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldClientRequestID, v))
}

// ClientRequestIDContainsFold applies the ContainsFold predicate on the "client_request_id" field.
func ClientRequestIDContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldClientRequestID, v))
}

// SelectedUpstreamIDEQ applies the EQ predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDNEQ applies the NEQ predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDIn applies the In predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldSelectedUpstreamID, vs...))
}

// SelectedUpstreamIDNotIn applies the NotIn predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldSelectedUpstreamID, vs...))
}

// SelectedUpstreamIDGT applies the GT predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDGTE applies the GTE predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDLT applies the LT predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDLTE applies the LTE predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDContains applies the Contains predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDHasPrefix applies the HasPrefix predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDHasSuffix applies the HasSuffix predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDEqualFold applies the EqualFold predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamIDContainsFold applies the ContainsFold predicate on the "selected_upstream_id" field.
func SelectedUpstreamIDContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldSelectedUpstreamID, v))
}

// SelectedUpstreamBaseURLEQ applies the EQ predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLNEQ applies the NEQ predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLIn applies the In predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldSelectedUpstreamBaseURL, vs...))
}

// SelectedUpstreamBaseURLNotIn applies the NotIn predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldSelectedUpstreamBaseURL, vs...))
}

// SelectedUpstreamBaseURLGT applies the GT predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLGTE applies the GTE predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLLT applies the LT predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLLTE applies the LTE predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLContains applies the Contains predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLHasPrefix applies the HasPrefix predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLHasSuffix applies the HasSuffix predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLEqualFold applies the EqualFold predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamBaseURLContainsFold applies the ContainsFold predicate on the "selected_upstream_base_url" field.
func SelectedUpstreamBaseURLContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldSelectedUpstreamBaseURL, v))
}

// SelectedUpstreamProviderPresetEQ applies the EQ predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetNEQ applies the NEQ predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetIn applies the In predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldSelectedUpstreamProviderPreset, vs...))
}

// SelectedUpstreamProviderPresetNotIn applies the NotIn predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldSelectedUpstreamProviderPreset, vs...))
}

// SelectedUpstreamProviderPresetGT applies the GT predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetGTE applies the GTE predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetLT applies the LT predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetLTE applies the LTE predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetContains applies the Contains predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetHasPrefix applies the HasPrefix predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetHasSuffix applies the HasSuffix predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetEqualFold applies the EqualFold predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldSelectedUpstreamProviderPreset, v))
}

// SelectedUpstreamProviderPresetContainsFold applies the ContainsFold predicate on the "selected_upstream_provider_preset" field.
func SelectedUpstreamProviderPresetContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldSelectedUpstreamProviderPreset, v))
}

// RoutingPolicyEQ applies the EQ predicate on the "routing_policy" field.
func RoutingPolicyEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingPolicy, v))
}

// RoutingPolicyNEQ applies the NEQ predicate on the "routing_policy" field.
func RoutingPolicyNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldRoutingPolicy, v))
}

// RoutingPolicyIn applies the In predicate on the "routing_policy" field.
func RoutingPolicyIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldRoutingPolicy, vs...))
}

// RoutingPolicyNotIn applies the NotIn predicate on the "routing_policy" field.
func RoutingPolicyNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldRoutingPolicy, vs...))
}

// RoutingPolicyGT applies the GT predicate on the "routing_policy" field.
func RoutingPolicyGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldRoutingPolicy, v))
}

// RoutingPolicyGTE applies the GTE predicate on the "routing_policy" field.
func RoutingPolicyGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldRoutingPolicy, v))
}

// RoutingPolicyLT applies the LT predicate on the "routing_policy" field.
func RoutingPolicyLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldRoutingPolicy, v))
}

// RoutingPolicyLTE applies the LTE predicate on the "routing_policy" field.
func RoutingPolicyLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldRoutingPolicy, v))
}

// RoutingPolicyContains applies the Contains predicate on the "routing_policy" field.
func RoutingPolicyContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldRoutingPolicy, v))
}

// RoutingPolicyHasPrefix applies the HasPrefix predicate on the "routing_policy" field.
func RoutingPolicyHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldRoutingPolicy, v))
}

// RoutingPolicyHasSuffix applies the HasSuffix predicate on the "routing_policy" field.
func RoutingPolicyHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldRoutingPolicy, v))
}

// RoutingPolicyEqualFold applies the EqualFold predicate on the "routing_policy" field.
func RoutingPolicyEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldRoutingPolicy, v))
}

// RoutingPolicyContainsFold applies the ContainsFold predicate on the "routing_policy" field.
func RoutingPolicyContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldRoutingPolicy, v))
}

// RoutingScoreEQ applies the EQ predicate on the "routing_score" field.
func RoutingScoreEQ(v float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingScore, v))
}

// RoutingScoreNEQ applies the NEQ predicate on the "routing_score" field.
func RoutingScoreNEQ(v float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldRoutingScore, v))
}

// RoutingScoreIn applies the In predicate on the "routing_score" field.
func RoutingScoreIn(vs ...float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldRoutingScore, vs...))
}

// RoutingScoreNotIn applies the NotIn predicate on the "routing_score" field.
func RoutingScoreNotIn(vs ...float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldRoutingScore, vs...))
}

// RoutingScoreGT applies the GT predicate on the "routing_score" field.
func RoutingScoreGT(v float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldRoutingScore, v))
}

// RoutingScoreGTE applies the GTE predicate on the "routing_score" field.
func RoutingScoreGTE(v float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldRoutingScore, v))
}

// RoutingScoreLT applies the LT predicate on the "routing_score" field.
func RoutingScoreLT(v float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldRoutingScore, v))
}

// RoutingScoreLTE applies the LTE predicate on the "routing_score" field.
func RoutingScoreLTE(v float64) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldRoutingScore, v))
}

// RoutingCandidateCountEQ applies the EQ predicate on the "routing_candidate_count" field.
func RoutingCandidateCountEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingCandidateCount, v))
}

// RoutingCandidateCountNEQ applies the NEQ predicate on the "routing_candidate_count" field.
func RoutingCandidateCountNEQ(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldRoutingCandidateCount, v))
}

// RoutingCandidateCountIn applies the In predicate on the "routing_candidate_count" field.
func RoutingCandidateCountIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldRoutingCandidateCount, vs...))
}

// RoutingCandidateCountNotIn applies the NotIn predicate on the "routing_candidate_count" field.
func RoutingCandidateCountNotIn(vs ...int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldRoutingCandidateCount, vs...))
}

// RoutingCandidateCountGT applies the GT predicate on the "routing_candidate_count" field.
func RoutingCandidateCountGT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldRoutingCandidateCount, v))
}

// RoutingCandidateCountGTE applies the GTE predicate on the "routing_candidate_count" field.
func RoutingCandidateCountGTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldRoutingCandidateCount, v))
}

// RoutingCandidateCountLT applies the LT predicate on the "routing_candidate_count" field.
func RoutingCandidateCountLT(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldRoutingCandidateCount, v))
}

// RoutingCandidateCountLTE applies the LTE predicate on the "routing_candidate_count" field.
func RoutingCandidateCountLTE(v int) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldRoutingCandidateCount, v))
}

// RoutingFailureReasonEQ applies the EQ predicate on the "routing_failure_reason" field.
func RoutingFailureReasonEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEQ(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonNEQ applies the NEQ predicate on the "routing_failure_reason" field.
func RoutingFailureReasonNEQ(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNEQ(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonIn applies the In predicate on the "routing_failure_reason" field.
func RoutingFailureReasonIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldIn(FieldRoutingFailureReason, vs...))
}

// RoutingFailureReasonNotIn applies the NotIn predicate on the "routing_failure_reason" field.
func RoutingFailureReasonNotIn(vs ...string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldNotIn(FieldRoutingFailureReason, vs...))
}

// RoutingFailureReasonGT applies the GT predicate on the "routing_failure_reason" field.
func RoutingFailureReasonGT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGT(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonGTE applies the GTE predicate on the "routing_failure_reason" field.
func RoutingFailureReasonGTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldGTE(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonLT applies the LT predicate on the "routing_failure_reason" field.
func RoutingFailureReasonLT(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLT(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonLTE applies the LTE predicate on the "routing_failure_reason" field.
func RoutingFailureReasonLTE(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldLTE(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonContains applies the Contains predicate on the "routing_failure_reason" field.
func RoutingFailureReasonContains(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContains(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonHasPrefix applies the HasPrefix predicate on the "routing_failure_reason" field.
func RoutingFailureReasonHasPrefix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasPrefix(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonHasSuffix applies the HasSuffix predicate on the "routing_failure_reason" field.
func RoutingFailureReasonHasSuffix(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldHasSuffix(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonEqualFold applies the EqualFold predicate on the "routing_failure_reason" field.
func RoutingFailureReasonEqualFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldEqualFold(FieldRoutingFailureReason, v))
}

// RoutingFailureReasonContainsFold applies the ContainsFold predicate on the "routing_failure_reason" field.
func RoutingFailureReasonContainsFold(v string) predicate.TraceLog {
	return predicate.TraceLog(sql.FieldContainsFold(FieldRoutingFailureReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TraceLog) predicate.TraceLog {
	return predicate.TraceLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TraceLog) predicate.TraceLog {
	return predicate.TraceLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TraceLog) predicate.TraceLog {
	return predicate.TraceLog(sql.NotPredicates(p))
}
