// Code generated by ent, DO NOT EDIT.

package upstreamtarget

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamtarget type in the database.
	Label = "upstream_target"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldProviderPreset holds the string denoting the provider_preset field in the database.
	FieldProviderPreset = "provider_preset"
	// FieldProtocolFamily holds the string denoting the protocol_family field in the database.
	FieldProtocolFamily = "protocol_family"
	// FieldRoutingProfile holds the string denoting the routing_profile field in the database.
	FieldRoutingProfile = "routing_profile"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldCapacityHint holds the string denoting the capacity_hint field in the database.
	FieldCapacityHint = "capacity_hint"
	// FieldLastRefreshAt holds the string denoting the last_refresh_at field in the database.
	FieldLastRefreshAt = "last_refresh_at"
	// FieldLastRefreshStatus holds the string denoting the last_refresh_status field in the database.
	FieldLastRefreshStatus = "last_refresh_status"
	// FieldLastRefreshError holds the string denoting the last_refresh_error field in the database.
	FieldLastRefreshError = "last_refresh_error"
	// Table holds the table name of the upstreamtarget in the database.
	Table = "upstream_targets"
)

// Columns holds all SQL columns for upstreamtarget fields.
var Columns = []string{
	FieldID,
	FieldBaseURL,
	FieldProviderPreset,
	FieldProtocolFamily,
	FieldRoutingProfile,
	FieldEnabled,
	FieldPriority,
	FieldWeight,
	FieldCapacityHint,
	FieldLastRefreshAt,
	FieldLastRefreshStatus,
	FieldLastRefreshError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBaseURL holds the default value on creation for the "base_url" field.
	DefaultBaseURL string
	// DefaultProviderPreset holds the default value on creation for the "provider_preset" field.
	DefaultProviderPreset string
	// DefaultProtocolFamily holds the default value on creation for the "protocol_family" field.
	DefaultProtocolFamily string
	// DefaultRoutingProfile holds the default value on creation for the "routing_profile" field.
	DefaultRoutingProfile string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight float64
	// DefaultCapacityHint holds the default value on creation for the "capacity_hint" field.
	DefaultCapacityHint float64
	// DefaultLastRefreshStatus holds the default value on creation for the "last_refresh_status" field.
	DefaultLastRefreshStatus string
	// DefaultLastRefreshError holds the default value on creation for the "last_refresh_error" field.
	DefaultLastRefreshError string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the UpstreamTarget queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByProviderPreset orders the results by the provider_preset field.
func ByProviderPreset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderPreset, opts...).ToFunc()
}

// ByProtocolFamily orders the results by the protocol_family field.
func ByProtocolFamily(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocolFamily, opts...).ToFunc()
}

// ByRoutingProfile orders the results by the routing_profile field.
func ByRoutingProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoutingProfile, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByCapacityHint orders the results by the capacity_hint field.
func ByCapacityHint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacityHint, opts...).ToFunc()
}

// ByLastRefreshAt orders the results by the last_refresh_at field.
func ByLastRefreshAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshAt, opts...).ToFunc()
}

// ByLastRefreshStatus orders the results by the last_refresh_status field.
func ByLastRefreshStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshStatus, opts...).ToFunc()
}

// ByLastRefreshError orders the results by the last_refresh_error field.
func ByLastRefreshError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshError, opts...).ToFunc()
}
