// Code generated by ent, DO NOT EDIT.

package upstreamtarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kingfs/llm-tracelab/ent/dao/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContainsFold(FieldID, id))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldBaseURL, v))
}

// ProviderPreset applies equality check predicate on the "provider_preset" field. It's identical to ProviderPresetEQ.
func ProviderPreset(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldProviderPreset, v))
}

// ProtocolFamily applies equality check predicate on the "protocol_family" field. It's identical to ProtocolFamilyEQ.
func ProtocolFamily(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldProtocolFamily, v))
}

// RoutingProfile applies equality check predicate on the "routing_profile" field. It's identical to RoutingProfileEQ.
func RoutingProfile(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldRoutingProfile, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldPriority, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldWeight, v))
}

// CapacityHint applies equality check predicate on the "capacity_hint" field. It's identical to CapacityHintEQ.
func CapacityHint(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldCapacityHint, v))
}

// LastRefreshAt applies equality check predicate on the "last_refresh_at" field. It's identical to LastRefreshAtEQ.
func LastRefreshAt(v time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldLastRefreshAt, v))
}

// LastRefreshStatus applies equality check predicate on the "last_refresh_status" field. It's identical to LastRefreshStatusEQ.
func LastRefreshStatus(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldLastRefreshStatus, v))
}

// LastRefreshError applies equality check predicate on the "last_refresh_error" field. It's identical to LastRefreshErrorEQ.
func LastRefreshError(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldLastRefreshError, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContainsFold(FieldBaseURL, v))
}

// ProviderPresetEQ applies the EQ predicate on the "provider_preset" field.
func ProviderPresetEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldProviderPreset, v))
}

// ProviderPresetNEQ applies the NEQ predicate on the "provider_preset" field.
func ProviderPresetNEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldProviderPreset, v))
}

// ProviderPresetIn applies the In predicate on the "provider_preset" field.
func ProviderPresetIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldProviderPreset, vs...))
}

// ProviderPresetNotIn applies the NotIn predicate on the "provider_preset" field.
func ProviderPresetNotIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldProviderPreset, vs...))
}

// ProviderPresetGT applies the GT predicate on the "provider_preset" field.
func ProviderPresetGT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldProviderPreset, v))
}

// ProviderPresetGTE applies the GTE predicate on the "provider_preset" field.
func ProviderPresetGTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldProviderPreset, v))
}

// ProviderPresetLT applies the LT predicate on the "provider_preset" field.
func ProviderPresetLT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldProviderPreset, v))
}

// ProviderPresetLTE applies the LTE predicate on the "provider_preset" field.
func ProviderPresetLTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldProviderPreset, v))
}

// ProviderPresetContains applies the Contains predicate on the "provider_preset" field.
func ProviderPresetContains(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContains(FieldProviderPreset, v))
}

// ProviderPresetHasPrefix applies the HasPrefix predicate on the "provider_preset" field.
func ProviderPresetHasPrefix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasPrefix(FieldProviderPreset, v))
}

// ProviderPresetHasSuffix applies the HasSuffix predicate on the "provider_preset" field.
func ProviderPresetHasSuffix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasSuffix(FieldProviderPreset, v))
}

// ProviderPresetEqualFold applies the EqualFold predicate on the "provider_preset" field.
func ProviderPresetEqualFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEqualFold(FieldProviderPreset, v))
}

// ProviderPresetContainsFold applies the ContainsFold predicate on the "provider_preset" field.
func ProviderPresetContainsFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContainsFold(FieldProviderPreset, v))
}

// ProtocolFamilyEQ applies the EQ predicate on the "protocol_family" field.
func ProtocolFamilyEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldProtocolFamily, v))
}

// ProtocolFamilyNEQ applies the NEQ predicate on the "protocol_family" field.
func ProtocolFamilyNEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldProtocolFamily, v))
}

// ProtocolFamilyIn applies the In predicate on the "protocol_family" field.
func ProtocolFamilyIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldProtocolFamily, vs...))
}

// ProtocolFamilyNotIn applies the NotIn predicate on the "protocol_family" field.
func ProtocolFamilyNotIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldProtocolFamily, vs...))
}

// ProtocolFamilyGT applies the GT predicate on the "protocol_family" field.
func ProtocolFamilyGT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldProtocolFamily, v))
}

// ProtocolFamilyGTE applies the GTE predicate on the "protocol_family" field.
func ProtocolFamilyGTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldProtocolFamily, v))
}

// ProtocolFamilyLT applies the LT predicate on the "protocol_family" field.
func ProtocolFamilyLT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldProtocolFamily, v))
}

// ProtocolFamilyLTE applies the LTE predicate on the "protocol_family" field.
func ProtocolFamilyLTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldProtocolFamily, v))
}

// ProtocolFamilyContains applies the Contains predicate on the "protocol_family" field.
func ProtocolFamilyContains(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContains(FieldProtocolFamily, v))
}

// ProtocolFamilyHasPrefix applies the HasPrefix predicate on the "protocol_family" field.
func ProtocolFamilyHasPrefix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasPrefix(FieldProtocolFamily, v))
}

// ProtocolFamilyHasSuffix applies the HasSuffix predicate on the "protocol_family" field.
func ProtocolFamilyHasSuffix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasSuffix(FieldProtocolFamily, v))
}

// ProtocolFamilyEqualFold applies the EqualFold predicate on the "protocol_family" field.
func ProtocolFamilyEqualFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEqualFold(FieldProtocolFamily, v))
}

// ProtocolFamilyContainsFold applies the ContainsFold predicate on the "protocol_family" field.
func ProtocolFamilyContainsFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContainsFold(FieldProtocolFamily, v))
}

// RoutingProfileEQ applies the EQ predicate on the "routing_profile" field.
func RoutingProfileEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldRoutingProfile, v))
}

// RoutingProfileNEQ applies the NEQ predicate on the "routing_profile" field.
func RoutingProfileNEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldRoutingProfile, v))
}

// RoutingProfileIn applies the In predicate on the "routing_profile" field.
func RoutingProfileIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldRoutingProfile, vs...))
}

// RoutingProfileNotIn applies the NotIn predicate on the "routing_profile" field.
func RoutingProfileNotIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldRoutingProfile, vs...))
}

// RoutingProfileGT applies the GT predicate on the "routing_profile" field.
func RoutingProfileGT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldRoutingProfile, v))
}

// RoutingProfileGTE applies the GTE predicate on the "routing_profile" field.
func RoutingProfileGTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldRoutingProfile, v))
}

// RoutingProfileLT applies the LT predicate on the "routing_profile" field.
func RoutingProfileLT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldRoutingProfile, v))
}

// RoutingProfileLTE applies the LTE predicate on the "routing_profile" field.
func RoutingProfileLTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldRoutingProfile, v))
}

// RoutingProfileContains applies the Contains predicate on the "routing_profile" field.
func RoutingProfileContains(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContains(FieldRoutingProfile, v))
}

// RoutingProfileHasPrefix applies the HasPrefix predicate on the "routing_profile" field.
func RoutingProfileHasPrefix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasPrefix(FieldRoutingProfile, v))
}

// RoutingProfileHasSuffix applies the HasSuffix predicate on the "routing_profile" field.
func RoutingProfileHasSuffix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasSuffix(FieldRoutingProfile, v))
}

// RoutingProfileEqualFold applies the EqualFold predicate on the "routing_profile" field.
func RoutingProfileEqualFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEqualFold(FieldRoutingProfile, v))
}

// RoutingProfileContainsFold applies the ContainsFold predicate on the "routing_profile" field.
func RoutingProfileContainsFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContainsFold(FieldRoutingProfile, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldPriority, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldWeight, v))
}

// CapacityHintEQ applies the EQ predicate on the "capacity_hint" field.
func CapacityHintEQ(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldCapacityHint, v))
}

// CapacityHintNEQ applies the NEQ predicate on the "capacity_hint" field.
func CapacityHintNEQ(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldCapacityHint, v))
}

// CapacityHintIn applies the In predicate on the "capacity_hint" field.
func CapacityHintIn(vs ...float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldCapacityHint, vs...))
}

// CapacityHintNotIn applies the NotIn predicate on the "capacity_hint" field.
func CapacityHintNotIn(vs ...float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldCapacityHint, vs...))
}

// CapacityHintGT applies the GT predicate on the "capacity_hint" field.
func CapacityHintGT(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldCapacityHint, v))
}

// CapacityHintGTE applies the GTE predicate on the "capacity_hint" field.
func CapacityHintGTE(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldCapacityHint, v))
}

// CapacityHintLT applies the LT predicate on the "capacity_hint" field.
func CapacityHintLT(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldCapacityHint, v))
}

// CapacityHintLTE applies the LTE predicate on the "capacity_hint" field.
func CapacityHintLTE(v float64) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldCapacityHint, v))
}

// LastRefreshAtEQ applies the EQ predicate on the "last_refresh_at" field.
func LastRefreshAtEQ(v time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtNEQ applies the NEQ predicate on the "last_refresh_at" field.
func LastRefreshAtNEQ(v time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtIn applies the In predicate on the "last_refresh_at" field.
func LastRefreshAtIn(vs ...time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtNotIn applies the NotIn predicate on the "last_refresh_at" field.
func LastRefreshAtNotIn(vs ...time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtGT applies the GT predicate on the "last_refresh_at" field.
func LastRefreshAtGT(v time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldLastRefreshAt, v))
}

// LastRefreshAtGTE applies the GTE predicate on the "last_refresh_at" field.
func LastRefreshAtGTE(v time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldLastRefreshAt, v))
}

// LastRefreshAtLT applies the LT predicate on the "last_refresh_at" field.
func LastRefreshAtLT(v time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldLastRefreshAt, v))
}

// LastRefreshAtLTE applies the LTE predicate on the "last_refresh_at" field.
func LastRefreshAtLTE(v time.Time) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldLastRefreshAt, v))
}

// LastRefreshAtIsNil applies the IsNil predicate on the "last_refresh_at" field.
func LastRefreshAtIsNil() predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIsNull(FieldLastRefreshAt))
}

// LastRefreshAtNotNil applies the NotNil predicate on the "last_refresh_at" field.
func LastRefreshAtNotNil() predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotNull(FieldLastRefreshAt))
}

// LastRefreshStatusEQ applies the EQ predicate on the "last_refresh_status" field.
func LastRefreshStatusEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldLastRefreshStatus, v))
}

// LastRefreshStatusNEQ applies the NEQ predicate on the "last_refresh_status" field.
func LastRefreshStatusNEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldLastRefreshStatus, v))
}

// LastRefreshStatusIn applies the In predicate on the "last_refresh_status" field.
func LastRefreshStatusIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldLastRefreshStatus, vs...))
}

// LastRefreshStatusNotIn applies the NotIn predicate on the "last_refresh_status" field.
func LastRefreshStatusNotIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldLastRefreshStatus, vs...))
}

// LastRefreshStatusGT applies the GT predicate on the "last_refresh_status" field.
func LastRefreshStatusGT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldLastRefreshStatus, v))
}

// LastRefreshStatusGTE applies the GTE predicate on the "last_refresh_status" field.
func LastRefreshStatusGTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldLastRefreshStatus, v))
}

// LastRefreshStatusLT applies the LT predicate on the "last_refresh_status" field.
func LastRefreshStatusLT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldLastRefreshStatus, v))
}

// LastRefreshStatusLTE applies the LTE predicate on the "last_refresh_status" field.
func LastRefreshStatusLTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldLastRefreshStatus, v))
}

// LastRefreshStatusContains applies the Contains predicate on the "last_refresh_status" field.
func LastRefreshStatusContains(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContains(FieldLastRefreshStatus, v))
}

// LastRefreshStatusHasPrefix applies the HasPrefix predicate on the "last_refresh_status" field.
func LastRefreshStatusHasPrefix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasPrefix(FieldLastRefreshStatus, v))
}

// LastRefreshStatusHasSuffix applies the HasSuffix predicate on the "last_refresh_status" field.
func LastRefreshStatusHasSuffix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasSuffix(FieldLastRefreshStatus, v))
}

// LastRefreshStatusEqualFold applies the EqualFold predicate on the "last_refresh_status" field.
func LastRefreshStatusEqualFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEqualFold(FieldLastRefreshStatus, v))
}

// LastRefreshStatusContainsFold applies the ContainsFold predicate on the "last_refresh_status" field.
func LastRefreshStatusContainsFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContainsFold(FieldLastRefreshStatus, v))
}

// LastRefreshErrorEQ applies the EQ predicate on the "last_refresh_error" field.
func LastRefreshErrorEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEQ(FieldLastRefreshError, v))
}

// LastRefreshErrorNEQ applies the NEQ predicate on the "last_refresh_error" field.
func LastRefreshErrorNEQ(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNEQ(FieldLastRefreshError, v))
}

// LastRefreshErrorIn applies the In predicate on the "last_refresh_error" field.
func LastRefreshErrorIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldIn(FieldLastRefreshError, vs...))
}

// LastRefreshErrorNotIn applies the NotIn predicate on the "last_refresh_error" field.
func LastRefreshErrorNotIn(vs ...string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldNotIn(FieldLastRefreshError, vs...))
}

// LastRefreshErrorGT applies the GT predicate on the "last_refresh_error" field.
func LastRefreshErrorGT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGT(FieldLastRefreshError, v))
}

// LastRefreshErrorGTE applies the GTE predicate on the "last_refresh_error" field.
func LastRefreshErrorGTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldGTE(FieldLastRefreshError, v))
}

// LastRefreshErrorLT applies the LT predicate on the "last_refresh_error" field.
func LastRefreshErrorLT(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLT(FieldLastRefreshError, v))
}

// LastRefreshErrorLTE applies the LTE predicate on the "last_refresh_error" field.
func LastRefreshErrorLTE(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldLTE(FieldLastRefreshError, v))
}

// LastRefreshErrorContains applies the Contains predicate on the "last_refresh_error" field.
func LastRefreshErrorContains(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContains(FieldLastRefreshError, v))
}

// LastRefreshErrorHasPrefix applies the HasPrefix predicate on the "last_refresh_error" field.
func LastRefreshErrorHasPrefix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasPrefix(FieldLastRefreshError, v))
}

// LastRefreshErrorHasSuffix applies the HasSuffix predicate on the "last_refresh_error" field.
func LastRefreshErrorHasSuffix(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldHasSuffix(FieldLastRefreshError, v))
}

// LastRefreshErrorEqualFold applies the EqualFold predicate on the "last_refresh_error" field.
func LastRefreshErrorEqualFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldEqualFold(FieldLastRefreshError, v))
}

// LastRefreshErrorContainsFold applies the ContainsFold predicate on the "last_refresh_error" field.
func LastRefreshErrorContainsFold(v string) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.FieldContainsFold(FieldLastRefreshError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamTarget) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamTarget) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamTarget) predicate.UpstreamTarget {
	return predicate.UpstreamTarget(sql.NotPredicates(p))
}
