// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/kingfs/llm-tracelab/ent/dao"
	"github.com/kingfs/llm-tracelab/ent/dao/apitoken"
	"github.com/kingfs/llm-tracelab/ent/dao/channelconfig"
	"github.com/kingfs/llm-tracelab/ent/dao/channelmodel"
	"github.com/kingfs/llm-tracelab/ent/dao/channelproberun"
	"github.com/kingfs/llm-tracelab/ent/dao/dataset"
	"github.com/kingfs/llm-tracelab/ent/dao/datasetexample"
	"github.com/kingfs/llm-tracelab/ent/dao/evalrun"
	"github.com/kingfs/llm-tracelab/ent/dao/experimentrun"
	"github.com/kingfs/llm-tracelab/ent/dao/modelcatalog"
	"github.com/kingfs/llm-tracelab/ent/dao/predicate"
	"github.com/kingfs/llm-tracelab/ent/dao/score"
	"github.com/kingfs/llm-tracelab/ent/dao/tracelog"
	"github.com/kingfs/llm-tracelab/ent/dao/upstreammodel"
	"github.com/kingfs/llm-tracelab/ent/dao/upstreamtarget"
	"github.com/kingfs/llm-tracelab/ent/dao/user"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next dao.Querier) dao.Querier {
	return dao.QuerierFunc(func(ctx context.Context, q dao.Query) (dao.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q dao.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The APITokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type APITokenFunc func(context.Context, *dao.APITokenQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f APITokenFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.APITokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.APITokenQuery", q)
}

// The TraverseAPIToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAPIToken func(context.Context, *dao.APITokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAPIToken) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAPIToken) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.APITokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.APITokenQuery", q)
}

// The ChannelConfigFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelConfigFunc func(context.Context, *dao.ChannelConfigQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f ChannelConfigFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.ChannelConfigQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.ChannelConfigQuery", q)
}

// The TraverseChannelConfig type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelConfig func(context.Context, *dao.ChannelConfigQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelConfig) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelConfig) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.ChannelConfigQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.ChannelConfigQuery", q)
}

// The ChannelModelFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelModelFunc func(context.Context, *dao.ChannelModelQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f ChannelModelFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.ChannelModelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.ChannelModelQuery", q)
}

// The TraverseChannelModel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelModel func(context.Context, *dao.ChannelModelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelModel) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelModel) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.ChannelModelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.ChannelModelQuery", q)
}

// The ChannelProbeRunFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelProbeRunFunc func(context.Context, *dao.ChannelProbeRunQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f ChannelProbeRunFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.ChannelProbeRunQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.ChannelProbeRunQuery", q)
}

// The TraverseChannelProbeRun type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelProbeRun func(context.Context, *dao.ChannelProbeRunQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelProbeRun) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelProbeRun) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.ChannelProbeRunQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.ChannelProbeRunQuery", q)
}

// The DatasetFunc type is an adapter to allow the use of ordinary function as a Querier.
type DatasetFunc func(context.Context, *dao.DatasetQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f DatasetFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.DatasetQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.DatasetQuery", q)
}

// The TraverseDataset type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDataset func(context.Context, *dao.DatasetQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDataset) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDataset) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.DatasetQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.DatasetQuery", q)
}

// The DatasetExampleFunc type is an adapter to allow the use of ordinary function as a Querier.
type DatasetExampleFunc func(context.Context, *dao.DatasetExampleQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f DatasetExampleFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.DatasetExampleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.DatasetExampleQuery", q)
}

// The TraverseDatasetExample type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDatasetExample func(context.Context, *dao.DatasetExampleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDatasetExample) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDatasetExample) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.DatasetExampleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.DatasetExampleQuery", q)
}

// The EvalRunFunc type is an adapter to allow the use of ordinary function as a Querier.
type EvalRunFunc func(context.Context, *dao.EvalRunQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f EvalRunFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.EvalRunQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.EvalRunQuery", q)
}

// The TraverseEvalRun type is an adapter to allow the use of ordinary function as Traverser.
type TraverseEvalRun func(context.Context, *dao.EvalRunQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseEvalRun) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseEvalRun) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.EvalRunQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.EvalRunQuery", q)
}

// The ExperimentRunFunc type is an adapter to allow the use of ordinary function as a Querier.
type ExperimentRunFunc func(context.Context, *dao.ExperimentRunQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f ExperimentRunFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.ExperimentRunQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.ExperimentRunQuery", q)
}

// The TraverseExperimentRun type is an adapter to allow the use of ordinary function as Traverser.
type TraverseExperimentRun func(context.Context, *dao.ExperimentRunQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseExperimentRun) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseExperimentRun) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.ExperimentRunQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.ExperimentRunQuery", q)
}

// The ModelCatalogFunc type is an adapter to allow the use of ordinary function as a Querier.
type ModelCatalogFunc func(context.Context, *dao.ModelCatalogQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f ModelCatalogFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.ModelCatalogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.ModelCatalogQuery", q)
}

// The TraverseModelCatalog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseModelCatalog func(context.Context, *dao.ModelCatalogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseModelCatalog) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseModelCatalog) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.ModelCatalogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.ModelCatalogQuery", q)
}

// The ScoreFunc type is an adapter to allow the use of ordinary function as a Querier.
type ScoreFunc func(context.Context, *dao.ScoreQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f ScoreFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.ScoreQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.ScoreQuery", q)
}

// The TraverseScore type is an adapter to allow the use of ordinary function as Traverser.
type TraverseScore func(context.Context, *dao.ScoreQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseScore) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseScore) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.ScoreQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.ScoreQuery", q)
}

// The TraceLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type TraceLogFunc func(context.Context, *dao.TraceLogQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f TraceLogFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.TraceLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.TraceLogQuery", q)
}

// The TraverseTraceLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTraceLog func(context.Context, *dao.TraceLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTraceLog) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTraceLog) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.TraceLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.TraceLogQuery", q)
}

// The UpstreamModelFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamModelFunc func(context.Context, *dao.UpstreamModelQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f UpstreamModelFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.UpstreamModelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.UpstreamModelQuery", q)
}

// The TraverseUpstreamModel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamModel func(context.Context, *dao.UpstreamModelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamModel) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamModel) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.UpstreamModelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.UpstreamModelQuery", q)
}

// The UpstreamTargetFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamTargetFunc func(context.Context, *dao.UpstreamTargetQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f UpstreamTargetFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.UpstreamTargetQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.UpstreamTargetQuery", q)
}

// The TraverseUpstreamTarget type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamTarget func(context.Context, *dao.UpstreamTargetQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamTarget) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamTarget) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.UpstreamTargetQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.UpstreamTargetQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *dao.UserQuery) (dao.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q dao.Query) (dao.Value, error) {
	if q, ok := q.(*dao.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *dao.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *dao.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next dao.Querier) dao.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q dao.Query) error {
	if q, ok := q.(*dao.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *dao.UserQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q dao.Query) (Query, error) {
	switch q := q.(type) {
	case *dao.APITokenQuery:
		return &query[*dao.APITokenQuery, predicate.APIToken, apitoken.OrderOption]{typ: dao.TypeAPIToken, tq: q}, nil
	case *dao.ChannelConfigQuery:
		return &query[*dao.ChannelConfigQuery, predicate.ChannelConfig, channelconfig.OrderOption]{typ: dao.TypeChannelConfig, tq: q}, nil
	case *dao.ChannelModelQuery:
		return &query[*dao.ChannelModelQuery, predicate.ChannelModel, channelmodel.OrderOption]{typ: dao.TypeChannelModel, tq: q}, nil
	case *dao.ChannelProbeRunQuery:
		return &query[*dao.ChannelProbeRunQuery, predicate.ChannelProbeRun, channelproberun.OrderOption]{typ: dao.TypeChannelProbeRun, tq: q}, nil
	case *dao.DatasetQuery:
		return &query[*dao.DatasetQuery, predicate.Dataset, dataset.OrderOption]{typ: dao.TypeDataset, tq: q}, nil
	case *dao.DatasetExampleQuery:
		return &query[*dao.DatasetExampleQuery, predicate.DatasetExample, datasetexample.OrderOption]{typ: dao.TypeDatasetExample, tq: q}, nil
	case *dao.EvalRunQuery:
		return &query[*dao.EvalRunQuery, predicate.EvalRun, evalrun.OrderOption]{typ: dao.TypeEvalRun, tq: q}, nil
	case *dao.ExperimentRunQuery:
		return &query[*dao.ExperimentRunQuery, predicate.ExperimentRun, experimentrun.OrderOption]{typ: dao.TypeExperimentRun, tq: q}, nil
	case *dao.ModelCatalogQuery:
		return &query[*dao.ModelCatalogQuery, predicate.ModelCatalog, modelcatalog.OrderOption]{typ: dao.TypeModelCatalog, tq: q}, nil
	case *dao.ScoreQuery:
		return &query[*dao.ScoreQuery, predicate.Score, score.OrderOption]{typ: dao.TypeScore, tq: q}, nil
	case *dao.TraceLogQuery:
		return &query[*dao.TraceLogQuery, predicate.TraceLog, tracelog.OrderOption]{typ: dao.TypeTraceLog, tq: q}, nil
	case *dao.UpstreamModelQuery:
		return &query[*dao.UpstreamModelQuery, predicate.UpstreamModel, upstreammodel.OrderOption]{typ: dao.TypeUpstreamModel, tq: q}, nil
	case *dao.UpstreamTargetQuery:
		return &query[*dao.UpstreamTargetQuery, predicate.UpstreamTarget, upstreamtarget.OrderOption]{typ: dao.TypeUpstreamTarget, tq: q}, nil
	case *dao.UserQuery:
		return &query[*dao.UserQuery, predicate.User, user.OrderOption]{typ: dao.TypeUser, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
