// Code generated by ent, DO NOT EDIT.

package upstreamexchange

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamexchange type in the database.
	Label = "upstream_exchange"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResponseID holds the string denoting the response_id field in the database.
	FieldResponseID = "response_id"
	// FieldRequestAuditID holds the string denoting the request_audit_id field in the database.
	FieldRequestAuditID = "request_audit_id"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldExchangeID holds the string denoting the exchange_id field in the database.
	FieldExchangeID = "exchange_id"
	// FieldExchangeKind holds the string denoting the exchange_kind field in the database.
	FieldExchangeKind = "exchange_kind"
	// FieldExchangeRole holds the string denoting the exchange_role field in the database.
	FieldExchangeRole = "exchange_role"
	// FieldParentExchangeID holds the string denoting the parent_exchange_id field in the database.
	FieldParentExchangeID = "parent_exchange_id"
	// FieldSequenceIndex holds the string denoting the sequence_index field in the database.
	FieldSequenceIndex = "sequence_index"
	// FieldCassettePath holds the string denoting the cassette_path field in the database.
	FieldCassettePath = "cassette_path"
	// FieldUpstreamID holds the string denoting the upstream_id field in the database.
	FieldUpstreamID = "upstream_id"
	// FieldRouteTarget holds the string denoting the route_target field in the database.
	FieldRouteTarget = "route_target"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldErrorText holds the string denoting the error_text field in the database.
	FieldErrorText = "error_text"
	// Table holds the table name of the upstreamexchange in the database.
	Table = "upstream_exchanges"
)

// Columns holds all SQL columns for upstreamexchange fields.
var Columns = []string{
	FieldID,
	FieldResponseID,
	FieldRequestAuditID,
	FieldTraceID,
	FieldExchangeID,
	FieldExchangeKind,
	FieldExchangeRole,
	FieldParentExchangeID,
	FieldSequenceIndex,
	FieldCassettePath,
	FieldUpstreamID,
	FieldRouteTarget,
	FieldModel,
	FieldEndpoint,
	FieldStatusCode,
	FieldStartedAt,
	FieldCompletedAt,
	FieldErrorText,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the UpstreamExchange queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResponseID orders the results by the response_id field.
func ByResponseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseID, opts...).ToFunc()
}

// ByRequestAuditID orders the results by the request_audit_id field.
func ByRequestAuditID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestAuditID, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// ByExchangeID orders the results by the exchange_id field.
func ByExchangeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeID, opts...).ToFunc()
}

// ByExchangeKind orders the results by the exchange_kind field.
func ByExchangeKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeKind, opts...).ToFunc()
}

// ByExchangeRole orders the results by the exchange_role field.
func ByExchangeRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeRole, opts...).ToFunc()
}

// ByParentExchangeID orders the results by the parent_exchange_id field.
func ByParentExchangeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentExchangeID, opts...).ToFunc()
}

// BySequenceIndex orders the results by the sequence_index field.
func BySequenceIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequenceIndex, opts...).ToFunc()
}

// ByCassettePath orders the results by the cassette_path field.
func ByCassettePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCassettePath, opts...).ToFunc()
}

// ByUpstreamID orders the results by the upstream_id field.
func ByUpstreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamID, opts...).ToFunc()
}

// ByRouteTarget orders the results by the route_target field.
func ByRouteTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteTarget, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByErrorText orders the results by the error_text field.
func ByErrorText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorText, opts...).ToFunc()
}
