-- create "experiment_runs" table
CREATE TABLE "experiment_runs" ("id" character varying NOT NULL, "name" character varying NOT NULL DEFAULT '', "description" character varying NOT NULL DEFAULT '', "baseline_eval_run_id" character varying NOT NULL, "candidate_eval_run_id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "baseline_score_count" bigint NOT NULL DEFAULT 0, "candidate_score_count" bigint NOT NULL DEFAULT 0, "baseline_pass_rate" double precision NOT NULL DEFAULT 0, "candidate_pass_rate" double precision NOT NULL DEFAULT 0, "pass_rate_delta" double precision NOT NULL DEFAULT 0, "matched_score_count" bigint NOT NULL DEFAULT 0, "improvement_count" bigint NOT NULL DEFAULT 0, "regression_count" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- create index "experimentrun_created_at_id" to table: "experiment_runs"
CREATE INDEX "experimentrun_created_at_id" ON "experiment_runs" ("created_at", "id");
-- create "request_audits" table
CREATE TABLE "request_audits" ("id" character varying NOT NULL, "response_id" character varying NULL, "conversation_id" character varying NULL, "method" character varying NOT NULL, "path" character varying NOT NULL, "client_request_id" character varying NULL, "header_json" jsonb NULL, "body_preview" character varying NULL, "body_sha256" character varying NULL, "redaction_json" jsonb NULL, "status" character varying NOT NULL DEFAULT '', "error_text" character varying NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "requestaudit_client_request_id" to table: "request_audits"
CREATE INDEX "requestaudit_client_request_id" ON "request_audits" ("client_request_id");
-- create index "requestaudit_conversation_id_created_at" to table: "request_audits"
CREATE INDEX "requestaudit_conversation_id_created_at" ON "request_audits" ("conversation_id", "created_at");
-- create index "requestaudit_response_id_created_at" to table: "request_audits"
CREATE INDEX "requestaudit_response_id_created_at" ON "request_audits" ("response_id", "created_at");
-- create index "requestaudit_status_created_at" to table: "request_audits"
CREATE INDEX "requestaudit_status_created_at" ON "request_audits" ("status", "created_at");
-- create "channel_models" table
CREATE TABLE "channel_models" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 47244640256), "channel_id" character varying NOT NULL, "model" character varying NOT NULL, "display_name" character varying NOT NULL DEFAULT '', "source" character varying NOT NULL DEFAULT '', "enabled" boolean NOT NULL DEFAULT true, "supports_responses" bigint NULL, "supports_chat_completions" bigint NULL, "supports_embeddings" bigint NULL, "context_window" bigint NULL, "input_modalities_json" character varying NOT NULL DEFAULT '[]', "output_modalities_json" character varying NOT NULL DEFAULT '[]', "raw_model_json" character varying NOT NULL DEFAULT '{}', "first_seen_at" timestamptz NOT NULL, "last_seen_at" timestamptz NOT NULL, "last_probe_at" timestamptz NULL, PRIMARY KEY ("id"));
-- create index "channelmodel_channel_id_enabled" to table: "channel_models"
CREATE INDEX "channelmodel_channel_id_enabled" ON "channel_models" ("channel_id", "enabled");
-- create index "channelmodel_channel_id_model" to table: "channel_models"
CREATE UNIQUE INDEX "channelmodel_channel_id_model" ON "channel_models" ("channel_id", "model");
-- create index "channelmodel_model" to table: "channel_models"
CREATE INDEX "channelmodel_model" ON "channel_models" ("model");
-- create "model_catalog" table
CREATE TABLE "model_catalog" ("model" character varying NOT NULL, "display_name" character varying NOT NULL DEFAULT '', "family" character varying NOT NULL DEFAULT '', "vendor" character varying NOT NULL DEFAULT '', "description" character varying NOT NULL DEFAULT '', "tags_json" character varying NOT NULL DEFAULT '[]', "first_seen_at" timestamptz NOT NULL, "last_seen_at" timestamptz NOT NULL, "last_used_at" timestamptz NULL, PRIMARY KEY ("model"));
-- create "datasets" table
CREATE TABLE "datasets" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "dataset_updated_at" to table: "datasets"
CREATE INDEX "dataset_updated_at" ON "datasets" ("updated_at");
-- create "dataset_examples" table
CREATE TABLE "dataset_examples" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 12884901888), "dataset_id" character varying NOT NULL, "trace_id" character varying NOT NULL, "position" bigint NOT NULL DEFAULT 0, "added_at" timestamptz NOT NULL, "source_type" character varying NOT NULL DEFAULT '', "source_id" character varying NOT NULL DEFAULT '', "note" character varying NOT NULL DEFAULT '', PRIMARY KEY ("id"));
-- create index "datasetexample_dataset_id_position" to table: "dataset_examples"
CREATE INDEX "datasetexample_dataset_id_position" ON "dataset_examples" ("dataset_id", "position");
-- create index "datasetexample_dataset_id_trace_id" to table: "dataset_examples"
CREATE UNIQUE INDEX "datasetexample_dataset_id_trace_id" ON "dataset_examples" ("dataset_id", "trace_id");
-- create "eval_runs" table
CREATE TABLE "eval_runs" ("id" character varying NOT NULL, "dataset_id" character varying NOT NULL DEFAULT '', "source_type" character varying NOT NULL DEFAULT '', "source_id" character varying NOT NULL DEFAULT '', "evaluator_set" character varying NOT NULL, "created_at" timestamptz NOT NULL, "completed_at" timestamptz NOT NULL, "trace_count" bigint NOT NULL DEFAULT 0, "score_count" bigint NOT NULL DEFAULT 0, "pass_count" bigint NOT NULL DEFAULT 0, "fail_count" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- create index "evalrun_created_at" to table: "eval_runs"
CREATE INDEX "evalrun_created_at" ON "eval_runs" ("created_at");
-- create "execution_events" table
CREATE TABLE "execution_events" ("id" character varying NOT NULL, "response_id" character varying NULL, "request_audit_id" character varying NULL, "conversation_id" character varying NULL, "event_type" character varying NOT NULL, "phase" character varying NOT NULL DEFAULT '', "status" character varying NOT NULL DEFAULT '', "message" character varying NULL, "details_json" jsonb NULL, "occurred_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "executionevent_conversation_id_occurred_at" to table: "execution_events"
CREATE INDEX "executionevent_conversation_id_occurred_at" ON "execution_events" ("conversation_id", "occurred_at");
-- create index "executionevent_event_type_occurred_at" to table: "execution_events"
CREATE INDEX "executionevent_event_type_occurred_at" ON "execution_events" ("event_type", "occurred_at");
-- create index "executionevent_phase_status_occurred_at" to table: "execution_events"
CREATE INDEX "executionevent_phase_status_occurred_at" ON "execution_events" ("phase", "status", "occurred_at");
-- create index "executionevent_request_audit_id_occurred_at" to table: "execution_events"
CREATE INDEX "executionevent_request_audit_id_occurred_at" ON "execution_events" ("request_audit_id", "occurred_at");
-- create index "executionevent_response_id_occurred_at" to table: "execution_events"
CREATE INDEX "executionevent_response_id_occurred_at" ON "execution_events" ("response_id", "occurred_at");
-- create "channel_configs" table
CREATE TABLE "channel_configs" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "source" character varying NOT NULL DEFAULT 'manual', "base_url" character varying NOT NULL, "provider_preset" character varying NOT NULL DEFAULT '', "protocol_family" character varying NOT NULL DEFAULT '', "routing_profile" character varying NOT NULL DEFAULT '', "api_version" character varying NOT NULL DEFAULT '', "deployment" character varying NOT NULL DEFAULT '', "project" character varying NOT NULL DEFAULT '', "location" character varying NOT NULL DEFAULT '', "model_resource" character varying NOT NULL DEFAULT '', "api_key_ciphertext" bytea NULL, "api_key_hint" character varying NOT NULL DEFAULT '', "headers_json" character varying NOT NULL DEFAULT '{}', "enabled" boolean NOT NULL DEFAULT true, "priority" bigint NOT NULL DEFAULT 0, "weight" double precision NOT NULL DEFAULT 1, "capacity_hint" double precision NOT NULL DEFAULT 1, "model_discovery" character varying NOT NULL DEFAULT 'list_models', "allow_unknown_models" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "last_probe_at" timestamptz NULL, "last_probe_status" character varying NOT NULL DEFAULT '', "last_probe_error" character varying NOT NULL DEFAULT '', PRIMARY KEY ("id"));
-- create index "channelconfig_enabled_priority" to table: "channel_configs"
CREATE INDEX "channelconfig_enabled_priority" ON "channel_configs" ("enabled", "priority");
-- create index "channelconfig_provider_preset" to table: "channel_configs"
CREATE INDEX "channelconfig_provider_preset" ON "channel_configs" ("provider_preset");
-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 4294967296), "username" character varying NOT NULL, "password_hash" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'admin', "enabled" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "last_login_at" timestamptz NULL, PRIMARY KEY ("id"));
-- create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- create "channel_probe_runs" table
CREATE TABLE "channel_probe_runs" ("id" character varying NOT NULL, "channel_id" character varying NOT NULL, "status" character varying NOT NULL, "started_at" timestamptz NOT NULL, "completed_at" timestamptz NULL, "duration_ms" bigint NOT NULL DEFAULT 0, "discovered_count" bigint NOT NULL DEFAULT 0, "enabled_count" bigint NOT NULL DEFAULT 0, "endpoint" character varying NOT NULL DEFAULT '', "status_code" bigint NOT NULL DEFAULT 0, "error_text" character varying NOT NULL DEFAULT '', "request_meta_json" character varying NOT NULL DEFAULT '{}', "response_sample_json" character varying NOT NULL DEFAULT '{}', PRIMARY KEY ("id"));
-- create index "channelproberun_channel_id_started_at" to table: "channel_probe_runs"
CREATE INDEX "channelproberun_channel_id_started_at" ON "channel_probe_runs" ("channel_id", "started_at");
-- create index "channelproberun_status_started_at" to table: "channel_probe_runs"
CREATE INDEX "channelproberun_status_started_at" ON "channel_probe_runs" ("status", "started_at");
-- create "responses" table
CREATE TABLE "responses" ("id" character varying NOT NULL, "conversation_id" character varying NOT NULL DEFAULT '', "previous_response_id" character varying NOT NULL DEFAULT '', "status" character varying NOT NULL DEFAULT 'queued', "model" character varying NOT NULL, "history_item_ids" jsonb NULL, "output_item_ids" jsonb NULL, "effective_tools" jsonb NULL, "metadata" jsonb NULL, "usage" jsonb NULL, "error" jsonb NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "response_conversation_id_created_at" to table: "responses"
CREATE INDEX "response_conversation_id_created_at" ON "responses" ("conversation_id", "created_at");
-- create index "response_previous_response_id" to table: "responses"
CREATE INDEX "response_previous_response_id" ON "responses" ("previous_response_id");
-- create index "response_status_created_at" to table: "responses"
CREATE INDEX "response_status_created_at" ON "responses" ("status", "created_at");
-- create "response_items" table
CREATE TABLE "response_items" ("id" character varying NOT NULL, "kind" character varying NOT NULL, "response_id" character varying NOT NULL DEFAULT '', "conversation_id" character varying NOT NULL DEFAULT '', "payload" jsonb NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "responseitem_conversation_id_created_at" to table: "response_items"
CREATE INDEX "responseitem_conversation_id_created_at" ON "response_items" ("conversation_id", "created_at");
-- create index "responseitem_response_id_kind" to table: "response_items"
CREATE INDEX "responseitem_response_id_kind" ON "response_items" ("response_id", "kind");
-- create "scores" table
CREATE TABLE "scores" ("id" character varying NOT NULL, "trace_id" character varying NOT NULL, "session_id" character varying NOT NULL DEFAULT '', "dataset_id" character varying NOT NULL DEFAULT '', "eval_run_id" character varying NOT NULL DEFAULT '', "evaluator_key" character varying NOT NULL, "value" double precision NOT NULL DEFAULT 0, "status" character varying NOT NULL DEFAULT '', "label" character varying NOT NULL DEFAULT '', "explanation" character varying NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "score_dataset_id_created_at" to table: "scores"
CREATE INDEX "score_dataset_id_created_at" ON "scores" ("dataset_id", "created_at");
-- create index "score_eval_run_id_created_at" to table: "scores"
CREATE INDEX "score_eval_run_id_created_at" ON "scores" ("eval_run_id", "created_at");
-- create index "score_session_id_created_at" to table: "scores"
CREATE INDEX "score_session_id_created_at" ON "scores" ("session_id", "created_at");
-- create index "score_trace_id_created_at" to table: "scores"
CREATE INDEX "score_trace_id_created_at" ON "scores" ("trace_id", "created_at");
-- create "logs" table
CREATE TABLE "logs" ("path" character varying NOT NULL, "trace_id" character varying NOT NULL, "mod_time_ns" bigint NOT NULL, "file_size" bigint NOT NULL, "version" character varying NOT NULL, "request_id" character varying NOT NULL DEFAULT '', "recorded_at" timestamptz NOT NULL, "model" character varying NOT NULL DEFAULT '', "provider" character varying NOT NULL DEFAULT '', "operation" character varying NOT NULL DEFAULT '', "endpoint" character varying NOT NULL DEFAULT '', "url" character varying NOT NULL DEFAULT '', "method" character varying NOT NULL DEFAULT '', "status_code" bigint NOT NULL DEFAULT 0, "duration_ms" bigint NOT NULL DEFAULT 0, "ttft_ms" bigint NOT NULL DEFAULT 0, "client_ip" character varying NOT NULL DEFAULT '', "content_length" bigint NOT NULL DEFAULT 0, "error_text" character varying NOT NULL DEFAULT '', "prompt_tokens" bigint NOT NULL DEFAULT 0, "completion_tokens" bigint NOT NULL DEFAULT 0, "total_tokens" bigint NOT NULL DEFAULT 0, "cached_tokens" bigint NOT NULL DEFAULT 0, "req_header_len" bigint NOT NULL DEFAULT 0, "req_body_len" bigint NOT NULL DEFAULT 0, "res_header_len" bigint NOT NULL DEFAULT 0, "res_body_len" bigint NOT NULL DEFAULT 0, "is_stream" boolean NOT NULL DEFAULT false, "session_id" character varying NOT NULL DEFAULT '', "session_source" character varying NOT NULL DEFAULT '', "window_id" character varying NOT NULL DEFAULT '', "client_request_id" character varying NOT NULL DEFAULT '', "selected_upstream_id" character varying NOT NULL DEFAULT '', "selected_upstream_base_url" character varying NOT NULL DEFAULT '', "selected_upstream_provider_preset" character varying NOT NULL DEFAULT '', "routing_policy" character varying NOT NULL DEFAULT '', "routing_score" double precision NOT NULL DEFAULT 0, "routing_candidate_count" bigint NOT NULL DEFAULT 0, "routing_failure_reason" character varying NOT NULL DEFAULT '', PRIMARY KEY ("path"));
-- create index "logs_trace_id_key" to table: "logs"
CREATE UNIQUE INDEX "logs_trace_id_key" ON "logs" ("trace_id");
-- create index "tracelog_model_recorded_at" to table: "logs"
CREATE INDEX "tracelog_model_recorded_at" ON "logs" ("model", "recorded_at");
-- create index "tracelog_recorded_at" to table: "logs"
CREATE INDEX "tracelog_recorded_at" ON "logs" ("recorded_at");
-- create index "tracelog_request_id" to table: "logs"
CREATE INDEX "tracelog_request_id" ON "logs" ("request_id");
-- create index "tracelog_session_id_recorded_at" to table: "logs"
CREATE INDEX "tracelog_session_id_recorded_at" ON "logs" ("session_id", "recorded_at");
-- create "upstream_exchanges" table
CREATE TABLE "upstream_exchanges" ("id" character varying NOT NULL, "response_id" character varying NULL, "request_audit_id" character varying NULL, "trace_id" character varying NULL, "cassette_path" character varying NULL, "upstream_id" character varying NULL, "route_target" character varying NULL, "model" character varying NULL, "endpoint" character varying NULL, "status_code" bigint NULL, "started_at" timestamptz NULL, "completed_at" timestamptz NULL, "error_text" character varying NULL, PRIMARY KEY ("id"));
-- create index "upstreamexchange_request_audit_id_started_at" to table: "upstream_exchanges"
CREATE INDEX "upstreamexchange_request_audit_id_started_at" ON "upstream_exchanges" ("request_audit_id", "started_at");
-- create index "upstreamexchange_response_id_started_at" to table: "upstream_exchanges"
CREATE INDEX "upstreamexchange_response_id_started_at" ON "upstream_exchanges" ("response_id", "started_at");
-- create index "upstreamexchange_status_code_started_at" to table: "upstream_exchanges"
CREATE INDEX "upstreamexchange_status_code_started_at" ON "upstream_exchanges" ("status_code", "started_at");
-- create index "upstreamexchange_trace_id" to table: "upstream_exchanges"
CREATE INDEX "upstreamexchange_trace_id" ON "upstream_exchanges" ("trace_id");
-- create index "upstreamexchange_upstream_id_started_at" to table: "upstream_exchanges"
CREATE INDEX "upstreamexchange_upstream_id_started_at" ON "upstream_exchanges" ("upstream_id", "started_at");
-- create "upstream_models" table
CREATE TABLE "upstream_models" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 34359738368), "upstream_id" character varying NOT NULL, "model" character varying NOT NULL, "source" character varying NOT NULL DEFAULT '', "seen_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "upstreammodel_model" to table: "upstream_models"
CREATE INDEX "upstreammodel_model" ON "upstream_models" ("model");
-- create index "upstreammodel_upstream_id_model" to table: "upstream_models"
CREATE UNIQUE INDEX "upstreammodel_upstream_id_model" ON "upstream_models" ("upstream_id", "model");
-- create "upstream_targets" table
CREATE TABLE "upstream_targets" ("id" character varying NOT NULL, "base_url" character varying NOT NULL DEFAULT '', "provider_preset" character varying NOT NULL DEFAULT '', "protocol_family" character varying NOT NULL DEFAULT '', "routing_profile" character varying NOT NULL DEFAULT '', "enabled" boolean NOT NULL DEFAULT true, "priority" bigint NOT NULL DEFAULT 0, "weight" double precision NOT NULL DEFAULT 0, "capacity_hint" double precision NOT NULL DEFAULT 0, "last_refresh_at" timestamptz NULL, "last_refresh_status" character varying NOT NULL DEFAULT '', "last_refresh_error" character varying NOT NULL DEFAULT '', PRIMARY KEY ("id"));
-- create "api_tokens" table
CREATE TABLE "api_tokens" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "token_hash" character varying NOT NULL, "prefix" character varying NOT NULL, "scope" character varying NOT NULL DEFAULT 'all', "enabled" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL, "expires_at" timestamptz NULL, "last_used_at" timestamptz NULL, "user_tokens" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "api_tokens_users_tokens" FOREIGN KEY ("user_tokens") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "api_tokens_token_hash_key" to table: "api_tokens"
CREATE UNIQUE INDEX "api_tokens_token_hash_key" ON "api_tokens" ("token_hash");
-- create index "apitoken_enabled" to table: "api_tokens"
CREATE INDEX "apitoken_enabled" ON "api_tokens" ("enabled");
-- create index "apitoken_prefix" to table: "api_tokens"
CREATE INDEX "apitoken_prefix" ON "api_tokens" ("prefix");
