// Code generated by ent, DO NOT EDIT.

package analysisrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the analysisrun type in the database.
	Label = "analysis_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldAnalyzer holds the string denoting the analyzer field in the database.
	FieldAnalyzer = "analyzer"
	// FieldAnalyzerVersion holds the string denoting the analyzer_version field in the database.
	FieldAnalyzerVersion = "analyzer_version"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldInputRef holds the string denoting the input_ref field in the database.
	FieldInputRef = "input_ref"
	// FieldOutputJSON holds the string denoting the output_json field in the database.
	FieldOutputJSON = "output_json"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the analysisrun in the database.
	Table = "analysis_runs"
)

// Columns holds all SQL columns for analysisrun fields.
var Columns = []string{
	FieldID,
	FieldTraceID,
	FieldSessionID,
	FieldKind,
	FieldAnalyzer,
	FieldAnalyzerVersion,
	FieldModel,
	FieldInputRef,
	FieldOutputJSON,
	FieldStatus,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTraceID holds the default value on creation for the "trace_id" field.
	DefaultTraceID string
	// DefaultSessionID holds the default value on creation for the "session_id" field.
	DefaultSessionID string
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// AnalyzerValidator is a validator for the "analyzer" field. It is called by the builders before save.
	AnalyzerValidator func(string) error
	// AnalyzerVersionValidator is a validator for the "analyzer_version" field. It is called by the builders before save.
	AnalyzerVersionValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultInputRef holds the default value on creation for the "input_ref" field.
	DefaultInputRef string
	// DefaultOutputJSON holds the default value on creation for the "output_json" field.
	DefaultOutputJSON string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AnalysisRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByAnalyzer orders the results by the analyzer field.
func ByAnalyzer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalyzer, opts...).ToFunc()
}

// ByAnalyzerVersion orders the results by the analyzer_version field.
func ByAnalyzerVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalyzerVersion, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByInputRef orders the results by the input_ref field.
func ByInputRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputRef, opts...).ToFunc()
}

// ByOutputJSON orders the results by the output_json field.
func ByOutputJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputJSON, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
